export type ReadingAnswer = { prompt: string; answer: string; matching?: boolean };
export type ReadingAnswerBank = { id: string; unit: number; title: string; kind: 'Fiction' | 'Nonfiction'; printedPage: number; pdfPage: number; answers: ReadingAnswer[] };
const exercisePdfPages: Record<number, number> = { 8: 17, 14: 29, 20: 41, 28: 57, 36: 73, 42: 85, 48: 97, 58: 117, 68: 137, 74: 149, 82: 165, 88: 177, 96: 193, 102: 205, 112: 225, 118: 237, 128: 257, 134: 269 };
const bank = (id:string,unit:number,title:string,kind:ReadingAnswerBank['kind'],printedPage:number,items:Array<[string,string,boolean?]>):ReadingAnswerBank => ({id,unit,title,kind,printedPage,pdfPage:exercisePdfPages[printedPage],answers:items.map(([prompt,answer,matching])=>({prompt,answer,matching}))});

// Answer key prepared by reading the supplied scanned anthology. Open-ended personal responses are omitted.
export const readingAnswerBanks: ReadingAnswerBank[] = [
 bank('moon',1,'Together Under the Moon','Fiction',8,[
  ['2a · Festival celebrated for less than 3,000 years?','False — it has been celebrated for more than 3,000 years.'],['2b · Hou Yi and Chang’e made the lanterns?','False — Li Ming and her cousin made them.'],['2c · Hou Yi’s wife was Chang’e?','True.'],['2d · Li Ming’s family celebrated at a park?','True.'],['3 · Best summary','c · Li Ming celebrates with her family and learns Chang’e’s story.'],['4 · Put the events in order','1. Li Ming cleans/prepares beds. 2. She and Grandmother make mooncakes. 3. Her aunt, uncle, and cousin arrive. 4. Grandmother tells Chang’e’s story. 5. The family celebrates at the park.']]),
 bank('community',1,'What’s Your Community?','Nonfiction',14,[
  ['2a · Adrian feels he belongs at his new school.','True.'],['2b · Adrian cannot take part in music class.','False — he feels the rhythm and claps or plays the beat.'],['2c · Māori people live in New England.','False — Māori people are Indigenous to New Zealand.'],['2d · Māori traditions include the haka.','True.'],['3 · Best summary of both blogs','b · Belonging to a community can make people feel happy and included.'],['4 · Why does Adrian love sign language?','Why does Adrian love sign language? — Because it feels like a secret language.',true],['4 · What does Adrian like about music class?','What does Adrian like about music class? — He can feel rhythm and clap to the beat.',true],['4 · What is poi?','What is poi? — A dance where you spin a ball on a string.',true],['4 · When is the haka performed?','When does the New Zealand team perform the haka? — Before each rugby game.',true]]),
 bank('fables',2,'The Dog and His Reflection; The Fox and the Crow; The Grasshopper and the Ant','Fiction',20,[
  ['2a · The dog found a juicy fish.','False — he found meat.'],['2b · The dog fought another dog.','False — it was his reflection.'],['2c · The fox tried to reach grapes.','True.'],['2d · The ant kept working instead of playing.','True.'],['3a · What was the dog looking for?','Food.'],['3b · Where did he go to eat?','To the river, where he saw his reflection.'],['3c · How did the fox try to reach the grapes?','He jumped, then stood on a log pushed under the vine.'],['3d · Why did the fox walk away?','He pretended the grapes were sour because he could not reach them.'],['3e · Who wanted the ant to play?','The grasshopper.'],['3f · When did the grasshopper ask for food?','In winter, after he had not prepared food.']]),
 bank('food',2,'Who’s in the Mood for Food?','Nonfiction',28,[
  ['2a · What kind of taste is umami?','Savory; tomatoes, fish, mushrooms, and soy sauce are examples.'],['2b · What do the Inuit eat?','Seal, walrus, and whale meat, as well as fish.'],['2c · What are arancini, and where are they from?','Fried rice balls from Italy.'],['2d · What are dumplings called in China?','Rice dumplings wrapped in bamboo leaves; they are called zongzi.'],['3.1 · What do people in space eat nowadays?','b · Dehydrated food.'],['3.2 · What did people think about breakfast?','b · They thought breakfast was not important.'],['3.3 · Where is the Monkey Buffet Festival?','c · Thailand.'],['3.4 · Why did people put food in cold streams?','a · To preserve it.']]),
 bank('leaf',3,'The Last Leaf on the Tree','Fiction',36,[
  ['2a · Beetrice could not fly to collect nectar.','False — she collected nectar from flowers.'],['2b · The bees used fresh leaves every day.','True.'],['2c · The last leaf fell just after Beetrice shouted.','True — it fell just afterward, though the story does not say she caused it.'],['2d · The tree never grew new leaves.','False — thousands of new leaves grew.'],['3 · Which activities did Beetrice do?','a · Collected nectar; b · Wrote poetry; e · Recycled fallen leaves.'],['4 · Sort events before, during, and after the tree had no leaves.','Before: collected nectar. While bare: wrote poetry; bees used dry fallen leaves. After new leaves grew: collected leaves and recycled them.'],['5 · What did the bees learn?','Recycle, protect trees that give shade, and use natural resources carefully.']]),
 bank('eco',3,'Eco Excellent!','Nonfiction',42,[
  ['1 · Four key-word blanks','a sea; b cleanup; c fights; d research.'],['2 · Best summary','b · Climate change is serious, and everyone can help the environment.'],['3 · Put events in order','1. The teacher teaches about climate change. 2. Class watches a Greta Thunberg video. 3. Greta is introduced as a 15-year-old Swedish activist. 4. The writer decides to help locally.'],['4 · Example graphic organizer','Claim: Beach cleanup is awesome. Evidence: plastic harms ocean animals; the cleanup inspired other towns to form groups.']]),
 bank('polly',4,'Polly the Painter; Sully the Sculptor','Fiction',48,[
  ['2a · What is Polly good at?','Painting quickly, especially scenes and vistas.'],['2b · What does she paint with?','A hose, not a brush.'],['2c · What does Sully do?','Sculpts statues from food.'],['2d · What materials does he avoid?','Metal, stone, plastic, glass, wood, and bone.'],['2e · How does Sully make statues?','He carves foods such as pancakes, fruit, pies, fish sticks, fries, cookies, cheese, and pasta.'],['2f · Why are his statues never displayed?','He eats them when he is done.'],['3.1 · Polly paints faster than other…','b · Artists.'],['3.2 · Polly paints fastest…','c · Portraits.'],['3.3 · Sully makes statues from…','c · Food.'],['3.4 · What material does Sully never use?','b · Metal.']]),
 bank('art',4,'The Mysteries in Works of Art','Nonfiction',58,[
  ['2a · Primary colors','Red, yellow, and blue.'],['2b · Secondary colors','Orange, green, and purple.'],['2c · How can artists create contrast?','Use complementary colors together, such as orange and blue or yellow and purple.'],['2d · Why use colors different from nature?','To express ideas, feelings, or a story rather than realistic colors.'],['2e · Why is light important?','It draws the viewer’s eyes to important elements and can create mood.']]),
 bank('ben',5,'Ben’s Backyard Adventure','Fiction',68,[
  ['2a · Why did Ben crawl through the hole?','He was looking for Pepper, who had disappeared.'],['2b · Where did he find Aarav?','In the greenhouse/tree-house area in Aarav’s backyard, by the snake tank.'],['2c · Where had Aarav lived before?','India.'],['3.1 · What do both boys like?','a · Animals.'],['3.2 · What do they have in common?','b · They love animals.'],['3.3 · How is Aarav different?','c · He is from India.']]),
 bank('mandy',5,'Traveling Mandy’s Tips for Kids','Nonfiction',74,[
  ['2a · What two things should you always pack?','Sunscreen and an umbrella.'],['2b · Where can you take a pizza tour?','New York City.'],['2c · When might you need to compromise?','When traveling with others and choosing activities.'],['2d · Why take a fluffy jacket?','It keeps you warm on a cold plane or train and can be a pillow.'],['2e · How can you pack socks to save space?','Roll them up.'],['2f · Who can play License Plate Bingo?','The people you are traveling with.'],['3a · Mandy recommends taking candy as a present.','True — she suggests a small present from your country.'],['3b · License Plate Bingo is a plane game.','False — it is for a car trip.'],['3c · Roll T-shirts and socks to save space.','True.'],['3d · There are many bridges on the Amazon River.','False.'],['3e · Mandy always packs headphones.','True — she says she always packs them to listen to music or watch a movie.']]),
 bank('gold',6,'Going for Gold','Fiction',82,[
  ['2 · Emile was the captain…','Emile was the captain — of the French Olympic rowing team.',true],['2 · René and Lucien…','René and Lucien — invited Emile to captain.',true],['2 · 1900 was the year…','1900 was the year — of the Olympic Games and World’s Fair.',true],['2 · In Paris, most men…','In Paris, most men — wore top hats and long coats.',true],['2 · At the race, Emile thought…','At the race, Emile thought — the Dutch rowers looked very strong.',true],['3 · Put events in order','1. Emile smiles, knowing he is too small to row but a great captain. 2. After rowing, Emile and Jacques go to the clubhouse. 3. René and Lucien ask Emile to captain. 4. Emile and Jacques travel to Paris. 5. They take the subway to the World’s Fair. 6. The Dutch congratulate the French after the semifinal. 7. The Dutch change captains. 8. The French team wins silver.']]),
 bank('sports',6,'Strange Sports Newsletter','Nonfiction',88,[
  ['2a · Zorbing can make you dizzy or sick.','True.'],['2b · Sophie Smith’s record was 657 worms.','False.'],['2c · An astronaut played moon golf in February 1971.','True — Alan Shepard did.'],['2d · Breaking your egg first wins an egg race.','False — the egg must stay unbroken.'],['2e · Kite surfers wear helmets.','True.'],['3.1 · Where do you ride a zorbing bubble?','c · Down a hill.'],['3.2 · A windsurfing sail is attached to a…','a · Board.'],['3.3 · Where is the worm-charming competition?','b · Cheshire, United Kingdom.'],['4 · Match the sports gear descriptions','Kites: fly in different shapes and colors. Golf clubs: used by Alan Shepard on the moon. Zorbs: large plastic balls people climb inside.',true]]),
 bank('liam',7,'King Liam and the Treasure of Tutankhamun','Fiction',96,[
  ['2a · Liam lost his library books.','No — his little brother took them.'],['2b · Bromley was scared by Liam shouting.','Yes.'],['2c · Ancient Egypt is Auntie Kas’s favorite subject.','Yes.'],['2d · They saw Tutankhamun’s tomb.','No — they saw treasures from the tomb.'],['3 · “What’s all this shouting?”','“What’s all this shouting?” — Mom.',true],['3 · “Here we are!”','“Here we are!” — Auntie Kas.',true],['3 · “Was King Tutankhamun a cat?”','“Was King Tutankhamun a cat?” — Noah.',true],['3 · “What’s he saying, Auntie Kas?”','“What’s he saying, Auntie Kas?” — Liam.',true],['4 · Example museum-visit timeline','Before: Liam is upset about his books; Auntie Kas invites them. During: they travel by subway and see the treasures. After: they head home for dinner and Liam is kinder to Noah.']]),
 bank('saga',7,'Saga’s Sword: Girl Finds 1,500-Year-Old Sword in a Lake','Nonfiction',102,[
  ['2a · Where was the sword found?','In a lake in Sweden.'],['2b · How many friends did Saga have?','The article does not say.'],['2c · Why did Saga’s family move to Sweden?','The article does not say.'],['2d · Who found the sword?','Saga Vanecek.'],['2e · What was the sword made from?','Metal, covered with wood and leather.'],['3 · Saga’s family moved…','Saga’s family moved — from the United States to Sweden.',true],['3 · Saga was looking for rocks…','Saga was looking for rocks — to throw into the water.',true],['3 · Saga’s family was amazed…','Saga’s family was amazed — because she found an ancient sword.',true],['3 · The sword was fragile…','The sword was fragile — because light and air can destroy it.',true],['4 · Complete the museum card','Ancient sword; metal, wood, leather; found in a Swedish lake; fragile and now preserved by the museum.']]),
 bank('peace',8,'The Peace Maker','Fiction',112,[
  ['2 · Three things people in Electric City could not do','Use drones, microwave ovens, and hologram senders.'],['3 · “What do you want, kid?”','“What do you want, kid?” — Giant Johnny.',true],['3 · “Be home at 6 o’clock for dinner, JJ!”','“Be home at 6 o’clock for dinner, JJ!” — JJ’s mom.',true],['3 · “I’m already wet.”','“I’m already wet.” — JJ.',true],['3 · “How can I help you?”','“How can I help you?” — Giant Marcus.',true],['4 · Example fact and opinion','Fact: JJ can calm people and help them make peace. Opinion: “I don’t think JJ is a strong superhero.”']]),
 bank('footprint',8,'Protecting the Environment: How to Lower Your Electricity Footprint','Nonfiction',118,[
  ['2 · Best summary','b · We can protect the environment by reducing our electricity footprint.'],['3.1 · When does your footprint increase?','a · When you use electrical appliances.'],['3.2 · How are fossil fuels related to electricity?','c · Fossil fuels can be used to make electricity.'],['3.3 · How can we keep a house cool?','c · Plant trees or shrubs outside.'],['4 · Example fact and opinion','Fact: Electricity generated from fossil fuels adds to a footprint. Opinion: “Planting trees is the best way to cool a house.”']]),
 bank('talent',9,'The Best Talent Show Ever!','Fiction',128,[
  ['2a · Cheerful and likes the new classmate','Alex.'],['2b · Shy and likes writing rhymes','Martina.'],['2c · Usually not kind to his sister','Ethan.'],['2d · Wants to bring a dog to the show','Tere.'],['2e · Great at dancing','Alex.'],['2f · Nervous about the show','Martina.'],['2g · Proud of his sister at the end','Ethan.'],['2h · Teacher says she is clever','Martina.'],['3a · Where are the students in Scene 1?','At school, in their classroom.'],['3b · How do the kids react to Martina’s rhymes?','They are impressed and praise her clever rhymes.'],['3c · Who chooses a robot dance?','Alex.'],['3d · When does the audience stand and clap?','When Alex finishes his robot dance and rap, near the end of the show.']]),
 bank('heroes',9,'My Musical Heroes','Nonfiction',134,[
  ['3a · Beethoven was born in Italy.','False — he was born in Germany.'],['3b · Ella Fitzgerald was the Queen of Jazz.','True.'],['3c · Elvis Presley was the King of Rock and Roll.','True.'],['3d · Rock and Roll is more complicated than jazz.','False.'],['4 · Best summary','b · The blogger shares three musical heroes, their musical styles, and their talents.'],['5a · Instrument a','Instrument a — woodwind.',true],['5b · Instrument b','Instrument b — percussion.',true],['5c · Instrument c','Instrument c — strings.',true],['5d · Instrument d','Instrument d — brass.',true],['5e · Instrument e','Instrument e — brass.',true],['5f · Instrument f','Instrument f — strings.',true],['5g · Instrument g','Instrument g — percussion.',true],['5h · Instrument h','Instrument h — woodwind.',true],['6a · A group of musicians','Orchestra.'],['6b · Making music up as you play','Improvisation.'],['6c · Makes music louder','Amplifier.'],['6d · A long musical work for an orchestra','Symphony.'],['7 · What is Luna’s main purpose?','c · To share the music she loves.']]),
];

// Vocabulary and word-work blanks from the same reading check pages.
const addKeyBlanks = (bankId: string, entries: Array<[string, string, boolean?]>) => {
  readingAnswerBanks.find((item) => item.id === bankId)?.answers.push(...entries.map(([prompt, answer, matching]) => ({ prompt, answer, matching })));
};
addKeyBlanks('moon', [['Key words · lotus dough','paste'],['Key words · food for good ___','luck'],['Key words · greedy and ___','wicked'],['Key words · festival treat','mooncake']]);
addKeyBlanks('community', [['Key words · language using hands','sign language'],['Key words · be unkind or hurt someone','bully'],['Key words · be a member of a group','belong'],['Key words · native to a place','Indigenous']]);
addKeyBlanks('fables', [['Key words · take something quickly','grab'],['Key words · full of juice','juicy'],['Key words · seed made by a plant','grain'],['Key words · crush food with your teeth','chew'],['Key words · plant that produces grapes','grapevine'],['Key words · color of gold','golden'],['Animal riddle a · tiny insect, black or red, with two antennae','ant'],['Animal riddle b · black bird that flies high and has scary eyes','owl'],['Animal riddle c · four legs, tail, and man’s best friend','dog']]);
addKeyBlanks('food', [['Key words · chocolate taste','dark'],['Key words · underground food-storage room','cellar'],['Key words · keep food from spoiling','preserve'],['Key words · salty food','olives'],['Key words · two ___ of crackers','packages'],['Key words · space food','dehydrated']]);
addKeyBlanks('leaf', [['Key words · move your head to see above','look up'],['Key words · scared or worried','frightened'],['Key words · unfriendly and not polite','rude'],['Key words · sweet liquid from flowers','nectar']]);
addKeyBlanks('eco', [['Key words · water body you swim in','sea'],['Key words · organized event to pick up litter','cleanup'],['Key words · Greta ___ climate change','fights'],['Key words · search for information','research']]);
addKeyBlanks('polly', [['Key words · water the garden with a','hose'],['Key words · honey is very','thick'],['Key words · a painting shows a','scene'],['Key words · throw paint in drops','splatter'],['Key words · make a sculpture','sculpt'],['Key words · very quickly','rapidly']]);
addKeyBlanks('art', [['Key words · two matching halves','symmetrical'],['Key words · shape of something','form'],['Key words · diagram of primary and secondary colors','color wheel'],['Key words · artist’s paint-board colors','palette']]);
addKeyBlanks('ben', [['Key words · sniff the grass','sniff'],['Key words · hot and damp weather','humid'],['Key words · notice a bird','spot'],['Key words · frightening or strange','creepy'],['Key words · figure something out','realize'],['Key words · empty space in the wall','hole']]);
addKeyBlanks('mandy', [['Key words · power up a device','charge'],['Key words · electronic item','device'],['Key words · road for fast long-distance travel','highway'],['Key words · car registration markers','license plates'],['Key words · clothes with creases','wrinkled']]);
addKeyBlanks('gold', [['Key words · underground city train','subway'],['Key words · race quickly','row'],['Key words · body part between neck and arm','shoulder'],['Key words · move your head to say yes','nod'],['Key words · boat-moving pole','oar'],['Key words · be in front during a race','lead']]);
addKeyBlanks('sports', [['Key words · keep safe from harm','protect'],['Key words · round air-filled ball','bubble'],['Key words · ride waves','surf'],['Key words · flat piece for surfing','board']]);
addKeyBlanks('liam', [['Key words · four-legged pet with a tail','dog'],['Key words · crowned male ruler','king'],['Key words · studies ancient objects','archeologist'],['Key words · paper entry to a museum','ticket']]);
addKeyBlanks('saga', [['Key words · part held in the hand','handle'],['Key words · Viking battle weapon','sword'],['Key words · very surprised','amazed'],['Key words · easily damaged','fragile'],['Key words · historic Scandinavian seafarer','Viking']]);
addKeyBlanks('peace', [['Key words · unable to understand clearly','confused'],['Key words · angry because something is difficult','frustrated'],['Key words · push forcefully','shove'],['Key words · produce or create energy','generate'],['Key words · important assignment','mission']]);
addKeyBlanks('footprint', [['Key words · pollute or make harmful','contaminate'],['Key words · appliance that dries wet clothes','clothes dryer'],['Key words · small device or tool','gadget'],['Key words · good for the environment','eco-friendly']]);
addKeyBlanks('talent', [['Key words · musical instrument for a beginner','recorder'],['Key words · laugh quietly','giggle'],['Key words · able and intelligent','clever'],['Key words · shout approval','cheer'],['Key words · instrument you shake to keep rhythm','tambourine'],['Key words · bend at the waist to show respect','bow']]);
