'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import BookPickerCard from './book-picker';
import TimerStage, { TIMER_EFFECTS, type TimerEffect } from './timer-effects';
import { timerSounds } from './timer-sounds';
import MascotFace, { mascotPictures } from './mascot-face';
import { Award, BadgeCheck, BellRing, Check, ChevronDown, Clock3, Gift, Heart, Pause, Play, Printer, RotateCcw, Sparkles, Star, Timer, Trophy, Users, X } from 'lucide-react';

type FunStudent = { id: string; name: string; avatar: string };
export type ClassroomThemeOption = { id: string; label: string };
export function displayStudentName(name:string){const parts=name.trim().split(/\s+/).filter(Boolean);return parts.length<2?parts[0]||name:`${parts[0]} ${parts.slice(1).map(part=>`${Array.from(part)[0]?.toLocaleUpperCase()||''}.`).join(' ')}`;}
type FunProps = { tool?: string; onToolChange?: (tool: string) => void; presentIds?: string[]; onRollCall?: () => void; classroomId: string; classroom: string; students: FunStudent[]; prizes: string[]; earned: number; themeOptions: readonly ClassroomThemeOption[]; currentTheme: string; onThemeChange: (classroomId: string, theme: string) => void };
type SurpriseIdea={emoji:string;title:string;prompt:string;answer?:string};
const goalKey=(id:string)=>`ezgili-class-goal-${id}`;
const surpriseIdeas:SurpriseIdea[]=[{emoji:'🕺',title:'Movement minute',prompt:'Stretch tall like a giraffe, then wiggle like a jellyfish!'},{emoji:'🎨',title:'Tiny art challenge',prompt:'Draw a happy monster using only three shapes.'},{emoji:'🧠',title:'Brain break riddle',prompt:'What has a face and two hands but no arms or legs?',answer:'A clock!'},{emoji:'🐙',title:'Animal trivia',prompt:'Which sea animal has three hearts?',answer:'An octopus!'},{emoji:'💛',title:'Kindness mission',prompt:'Give someone a specific compliment about their effort.'},{emoji:'🎤',title:'Silly speaking prompt',prompt:'If your pencil could talk, what would it say today?'},{emoji:'🐾',title:'Animal stretch',prompt:'Move like a cat, a flamingo, and a sleepy bear!'},{emoji:'🌈',title:'Gratitude sparkle',prompt:'Name one small thing that made you smile this week.'}];
const kindnessBadges=[['💛','Kind heart'],['💪','Brave try'],['🤝','Helpful teammate'],['🎤','Bold speaker'],['🌱','Growth mindset'],['✨','Super effort']];
const mascotChoices=['🦊','🦁','🐼','🐸','🦄','🐬','🦉','🐢','🐯','🐙','🐻','🦋'];
const timerPresets=[10/60,0.5,1,3,5,10,15,20];
const presetLabel=(minutes:number)=>minutes<1?`${Math.round(minutes*60)} sec`:`${minutes} min`;
const themeSwatches:Record<string,string>={sunshine:'#f4bd32',ocean:'#278cc7',lavender:'#8b68d8',coral:'#f07878',forest:'#398a59',mint:'#51bda1',sky:'#55aee8',peach:'#f39a63',berry:'#d84d83',grape:'#7449bd',lagoon:'#20a5a6',cherry:'#d84354',lemon:'#cfbd27',aqua:'#20b9c1',tangerine:'#ed792e',rose:'#e554a4',indigo:'#4b50ba',seafoam:'#66b89a',denim:'#416caa',orchid:'#b34ab5',cocoa:'#946044',lime:'#83b72d'};
type LocalData={goals:Record<string,number>;mascots:Record<string,{emoji:string;name:string}>;badges:Record<string,Record<string,string[]>>;votes:Record<string,Record<string,string>>;celebrationSound:'applause'|'gentle'|'silent';celebrationConfetti:boolean};
const defaultData:LocalData={goals:{},mascots:{},badges:{},votes:{},celebrationSound:'applause',celebrationConfetti:true};
function saveLocal(data:LocalData){try{localStorage.setItem('ezgili-classroom-fun',JSON.stringify(data));window.dispatchEvent(new Event('ezgili-classroom-fun-updated'));}catch{}}
function getLocal():LocalData{try{const saved=JSON.parse(localStorage.getItem('ezgili-classroom-fun')||'{}');return {...defaultData,...saved,goals:saved.goals||{},mascots:saved.mascots||{},badges:saved.badges||{},votes:saved.votes||{}};}catch{return defaultData;}}
export function ClassGoalMeter({classroomId,earned}:{classroomId:string;earned:number}){
  const [goal,setGoal]=useState(20);
  useEffect(()=>{const read=()=>{try{const data=getLocal();setGoal(Number(data.goals[classroomId])||20);}catch{setGoal(20);}};read();window.addEventListener('ezgili-classroom-fun-updated',read);return()=>window.removeEventListener('ezgili-classroom-fun-updated',read);},[classroomId]);
  if(!classroomId)return null;
  const progress=Math.min(100,Math.round(earned/Math.max(goal,1)*100));
  return <section className="fun-goal-strip"><div className="fun-goal-icon">🌈</div><div className="fun-goal-copy"><strong>Our class goal</strong><span>{earned} of {goal} stars · {progress>=100?'We did it!':'Every little effort counts'}</span><div className="fun-goal-track"><i style={{width:`${progress}%`}}/></div></div><span className="fun-goal-percent">{progress}%</span></section>;
}
const toolTiles=[{id:'picker',label:'Who’s next?',emoji:'🎯'},{id:'timer',label:'Timer',emoji:'⏱️'},{id:'book',label:'Our Readers',emoji:'📚'},{id:'badges',label:'Badges',emoji:'💛'},{id:'goal',label:'Class goal',emoji:'🌈'},{id:'vote',label:'Class vote',emoji:'🗳️'},{id:'surprise',label:'Surprise',emoji:'🎲'},{id:'colors',label:'Colors',emoji:'🎨'},{id:'mascot',label:'Mascot',emoji:'🦊'},{id:'certificate',label:'Certificate',emoji:'🏅'}];
export default function ClassroomFun({tool:toolProp,onToolChange,presentIds,onRollCall,classroomId,classroom,students,prizes,earned,themeOptions,currentTheme,onThemeChange}:FunProps){
  const [data,setData]=useState<LocalData>(defaultData);
  const [localTool,setLocalTool]=useState('picker');
  const tool=toolProp??localTool;
  const chooseTool=(next:string)=>{setLocalTool(next);onToolChange?.(next);};
  const pane=(id:string)=>`tool-pane${tool===id?' is-active':''}`;
  const pool=presentIds?students.filter(s=>presentIds.includes(s.id)):students;
  const [candidate,setCandidate]=useState<FunStudent|null>(null);
  const [picking,setPicking]=useState(false);
  const pickRef=useRef<ReturnType<typeof setTimeout>|null>(null);
  const [badgeStudent,setBadgeStudent]=useState('');
  const [voteStudent,setVoteStudent]=useState('');
  const [customGoal,setCustomGoal]=useState('');
  const [mascotName,setMascotName]=useState('');
  const [certificate,setCertificate]=useState<FunStudent|null>(null);
  const [goalCelebration,setGoalCelebration]=useState(false);
  const [duration,setDuration]=useState(300);
  const [remaining,setRemaining]=useState(300);
  const [running,setRunning]=useState(false);
  const [timerFull,setTimerFull]=useState(false);
  const [activity,setActivity]=useState('Quiet reading');
  const [surpriseIndex,setSurpriseIndex]=useState(0);
  const [showSurpriseAnswer,setShowSurpriseAnswer]=useState(false);
  const [showAllBadges,setShowAllBadges]=useState(false);
  const [themeSpin,setThemeSpin]=useState(false);
  const [themePreview,setThemePreview]=useState(currentTheme);
  const themeSpinRef=useRef<ReturnType<typeof setTimeout>|null>(null);
  const [timerEffect,setTimerEffect]=useState<TimerEffect>('ring');
  const [timerSound,setTimerSound]=useState(true);
  useEffect(()=>{try{const saved=localStorage.getItem('ezgili-timer-effect');if(saved==='neon'||saved==='bomb'||saved==='ring')setTimerEffect(saved);setTimerSound(localStorage.getItem('ezgili-timer-sound')!=='off');}catch{}},[]);
  const chooseEffect=(next:TimerEffect)=>{setTimerEffect(next);try{localStorage.setItem('ezgili-timer-effect',next);}catch{}};
  const toggleSound=()=>{const on=!timerSound;setTimerSound(on);try{localStorage.setItem('ezgili-timer-sound',on?'on':'off');}catch{}if(on)timerSounds.unlock();else timerSounds.stop();};
  const lastRemaining=useRef(remaining);
  useEffect(()=>{const previous=lastRemaining.current;lastRemaining.current=remaining;if(!timerSound)return;if(running&&remaining<previous&&remaining>0)timerSounds.second(timerEffect,remaining);if(previous===1&&remaining===0)timerSounds.finish(timerEffect);// eslint-disable-next-line react-hooks/exhaustive-deps
  },[remaining]);
  useEffect(()=>{timerSounds.fuse(timerEffect==='bomb'&&running&&timerSound);return()=>timerSounds.fuse(false);},[running,timerEffect,timerSound]);  const mascot=data.mascots[classroomId]||{emoji:'🦊',name:'Champs'};
  const votes=data.votes[classroomId]||{};
  const awarded=data.badges[classroomId]||{};
  const goal=Number(data.goals[classroomId])||20;
  const progress=Math.min(100,Math.round(earned/Math.max(goal,1)*100));
  const selectedStudent=students.find(s=>s.id===badgeStudent);
  const selectedVoter=students.find(s=>s.id===voteStudent);
  const voteCounts=useMemo(()=>Object.values(votes).reduce<Record<string,number>>((counts,prize)=>({...counts,[prize]:(counts[prize]||0)+1}),{}),[votes]);
  useEffect(()=>{const initial=getLocal();setData(initial);setCustomGoal(String(initial.goals[classroomId]||20));setMascotName(initial.mascots[classroomId]?.name||'Champs');setBadgeStudent(students[0]?.id||'');setVoteStudent(students[0]?.id||'');setShowSurpriseAnswer(false);const day=new Date();setSurpriseIndex((Math.floor((Date.UTC(day.getFullYear(),day.getMonth(),day.getDate())-Date.UTC(day.getFullYear(),0,0))/86400000))%surpriseIdeas.length);},[classroomId]);
  useEffect(()=>{if(students.length&&!students.some(student=>student.id===badgeStudent))setBadgeStudent(students[0].id);if(students.length&&!students.some(student=>student.id===voteStudent))setVoteStudent(students[0].id);},[students,badgeStudent,voteStudent]);
  useEffect(()=>{if(!running)return;const interval=setInterval(()=>setRemaining(current=>{if(current<=1){setRunning(false);return 0;}return current-1;}),1000);return()=>clearInterval(interval);},[running]);
  useEffect(()=>()=>{if(pickRef.current)clearTimeout(pickRef.current);},[]);
  useEffect(()=>{setThemePreview(currentTheme);},[currentTheme]);
  useEffect(()=>()=>{if(themeSpinRef.current)clearTimeout(themeSpinRef.current);},[]);
  useEffect(()=>{if(!timerFull)return;const onKey=(event:KeyboardEvent)=>{if(event.key==='Escape')setTimerFull(false);};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);},[timerFull]);
  const update=(next:LocalData)=>{setData(next);saveLocal(next);};
  const startPicker=()=>{if(!pool.length||picking)return;setPicking(true);let turns=0;const spin=()=>{const next=pool[Math.floor(Math.random()*pool.length)];setCandidate(next);turns++;if(turns<18)pickRef.current=setTimeout(spin,65+turns*12);else setPicking(false);};spin();};
  const spinTheme=()=>{if(themeSpin||!themeOptions.length)return;setThemeSpin(true);let turns=0;const choices=themeOptions.filter(theme=>theme.id!==currentTheme);const pool=choices.length?choices:themeOptions;const chosen=pool[Math.floor(Math.random()*pool.length)];const spin=()=>{setThemePreview(themeOptions[turns%themeOptions.length].id);turns++;if(turns<20){themeSpinRef.current=setTimeout(spin,45+turns*11);return;}setThemePreview(chosen.id);setThemeSpin(false);onThemeChange(classroomId,chosen.id);};spin();};
  const adjustGoal=()=>{const value=Math.max(1,Math.min(100000,Number(customGoal)||20));setCustomGoal(String(value));update({...data,goals:{...data.goals,[classroomId]:value}});};
  const saveMascot=()=>update({...data,mascots:{...data.mascots,[classroomId]:{...mascot,name:mascotName.trim()||'Champs'}}});
  const awardBadge=(badge:string)=>{if(!selectedStudent)return;const list=awarded[selectedStudent.id]||[];if(list.includes(badge))return;update({...data,badges:{...data.badges,[classroomId]:{...awarded,[selectedStudent.id]:[...list,badge]}}});};
  const castVote=(prize:string)=>{if(!selectedVoter)return;update({...data,votes:{...data.votes,[classroomId]:{...votes,[selectedVoter.id]:prize}}});};
  const startTimer=()=>{if(remaining===0)setRemaining(duration);timerSounds.unlock();if(timerSound)timerSounds.start(timerEffect);setRunning(true);};
  const setPreset=(minutes:number)=>{const seconds=Math.round(minutes*60);setDuration(seconds);setRemaining(seconds);setRunning(false);};
  const resetTimer=()=>{setRunning(false);setRemaining(duration);};
  const clock=`${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}`;
  const ringProgress=1-remaining/Math.max(1,duration);
  const effectPicker=<div className="timer-effects" role="group" aria-label="Timer look and sound"><div className="timer-effect-chips">{TIMER_EFFECTS.map(e=><button key={e.id} type="button" className={`timer-effect-chip${timerEffect===e.id?' on':''}`} aria-pressed={timerEffect===e.id} onClick={()=>chooseEffect(e.id)}><span aria-hidden="true">{e.emoji}</span> {e.label}</button>)}</div><button type="button" className={`timer-sound-btn${timerSound?' on':''}`} aria-pressed={timerSound} onClick={toggleSound}>{timerSound?'🔊 Sound on':'🔇 Sound off'}</button></div>;
  const timerContent=<><div className="fun-timer-head"><div className="fun-panel-icon timer-icon"><Timer size={19}/></div><div><h2>Activity timer</h2><p>A lovely little focus session for {classroom}.</p></div><button className="fun-expand" onClick={()=>setTimerFull(true)} aria-label="Open full-screen timer" title="Full screen"><span>⛶</span></button></div>{effectPicker}<label className="fun-label" htmlFor="activity-name">What are we doing?</label><input id="activity-name" className="fun-input" value={activity} maxLength={45} onChange={e=>setActivity(e.target.value)} placeholder="e.g. Quiet reading"/><div className="fun-presets">{timerPresets.map(minutes=><button key={minutes} className={duration===Math.round(minutes*60)?'chosen':''} onClick={()=>setPreset(minutes)} disabled={running}>{presetLabel(minutes)}</button>)}</div><div className={`fun-timer-clock${timerEffect==='ring'?'':' has-effect'}`}>{timerEffect!=='ring'&&<TimerStage effect={timerEffect} remaining={remaining} duration={duration} running={running} clock={clock} size="card"/>}<div className="fun-clock-ring" style={{'--timer-progress':`${ringProgress*100}%`} as React.CSSProperties}><Clock3 size={21}/><strong>{clock}</strong><span>{remaining===0?'Time to celebrate!':running?'You’ve got this!':'Ready when you are'}</span></div></div><div className="fun-timer-actions"><button className="fun-action primary" onClick={running?()=>setRunning(false):startTimer}>{running?<><Pause size={17}/> Pause</>:<><Play size={17}/> {remaining===0?'Start again':'Start timer'}</>}</button><button className="fun-action secondary" onClick={resetTimer}><RotateCcw size={16}/> Reset</button><button className="fun-action secondary" onClick={()=>setTimerFull(true)}>Full screen</button></div>{remaining===0&&<div className="fun-timer-finished" role="status">🌟 Wonderful focus, {classroom}! Take a stretch break.</div>}</>;
  return <div className="classroom-fun-page">
    <div className="fun-presence"><button type="button" className="fun-presence-btn" onClick={onRollCall}>📋 Roll call</button><span>{presentIds?`${presentIds.length} of ${students.length} students are here`:'Everyone counts as here until you take roll call'}</span></div><div className="tool-launcher" role="tablist" aria-label="Classroom tools">{toolTiles.map(t=><button key={t.id} type="button" role="tab" aria-selected={tool===t.id} className={`tool-tile${tool===t.id?' is-active':''}`} onClick={()=>chooseTool(t.id)}><span className="tool-tile-icon" aria-hidden="true">{t.emoji}</span><span className="tool-tile-label">{t.label}</span></button>)}</div>
    <section className={`fun-goal-card ${pane('goal')}`}><div className="fun-goal-top"><span className="fun-feature-emoji">🌈</span><div><span className="fun-kicker">TEAMWORK MAKES THE DREAM WORK</span><h2>{progress>=100?'Our class did it!':`Our ${classroom} class goal`}</h2><p>{progress>=100?'High fives all around. Pick a new goal to keep the joy going!':'Every effort adds another star to our shared goal.'}</p></div><span className="fun-goal-medal">{progress>=100?'🏆':'⭐'}</span></div><div className="fun-goal-track large"><i style={{width:`${progress}%`}}/></div><div className="fun-goal-bottom"><strong>{earned} <small>of {goal} stars</small></strong><label>Goal <input aria-label="Set class star goal" type="number" min="1" max="100000" value={customGoal} onChange={e=>setCustomGoal(e.target.value)} onBlur={adjustGoal} onKeyDown={e=>{if(e.key==='Enter')adjustGoal()}}/></label></div>{progress>=100&&<button className="fun-action primary goal-celebrate-button" onClick={()=>setGoalCelebration(true)}>🎉 Celebrate our class goal!</button>}</section>
    <div className="fun-feature-grid">
      <section className={`fun-card theme-picker-card ${pane('colors')}`}><div className="fun-card-title"><div className="fun-panel-icon theme-picker-icon"><Sparkles size={18}/></div><div><h2>Pick our Champs colors!</h2><p>Give the whole {classroom} classroom a colorful surprise.</p></div></div><div className={`theme-randomizer-display ${themeSpin?'is-spinning':''}`} aria-live="polite"><span className="theme-randomizer-orb" style={{'--theme-swatch':themeSwatches[themePreview]||'#8b68d8'} as React.CSSProperties}>✦</span><div><small>{themeSpin?'COLOR SPINNING…':'YOUR CLASSROOM COLOR'}</small><strong>{themeOptions.find(theme=>theme.id===themePreview)?.label||'Sunshine yellow'}</strong></div><div className="theme-randomizer-dots" aria-hidden="true">{themeOptions.slice(0,8).map(theme=><i key={theme.id} style={{background:themeSwatches[theme.id]}}/>)}</div></div><button className="fun-action primary full" disabled={themeSpin||!themeOptions.length} onClick={spinTheme}><Sparkles size={17}/>{themeSpin?'Spinning for a color…':'Surprise us with a color!'}</button><p className="theme-randomizer-hint">Press the button to randomly change the colors across your classroom.</p></section>
      <section className={`fun-card picker-card ${pane('picker')}`}><div className="fun-card-title"><div className="fun-panel-icon picker-icon"><Users size={18}/></div><div><h2>Who’s up next?</h2><p>Let the Champs picker choose fairly.</p></div></div><div className={`picker-stage ${picking?'is-picking':''}`}><span className="picker-confetti" aria-hidden="true">✦　✧　✿</span><span className="picker-avatar">{candidate?.avatar||'🎁'}</span><strong>{candidate?displayStudentName(candidate.name):(students.length?'Ready for a surprise?':'Add students to start!')}</strong><small>{picking?'Picking a lucky learner…':candidate?'You’re our superstar!':'Everyone has an equal chance.'}</small></div><p className="present-chip">{presentIds?<>✅ Picking from <b>{pool.length}</b> student{pool.length===1?'':'s'} who are here</>:<>Everyone is in the draw</>} <button type="button" className="text-link" onClick={onRollCall}>{presentIds?'Change':'Take roll call'}</button></p><button className="fun-action primary full" disabled={!pool.length||picking} onClick={startPicker}><Sparkles size={17}/>{picking?'Picking…':'Pick a student!'}</button>{candidate&&!picking&&<button className="fun-text-action" onClick={()=>setCertificate(candidate)}>Make a certificate for {displayStudentName(candidate.name)}</button>}</section>
      <section className={`fun-card daily-card ${pane('surprise')}`}><div className="fun-card-title"><div className="fun-panel-icon daily-icon"><Gift size={18}/></div><div><h2>Today’s surprise</h2><p>A tiny idea for a brighter day.</p></div></div><div className="daily-surprise"><span>{surpriseIdeas[surpriseIndex].emoji}</span><div><small>CLASSROOM CHALLENGE</small><h3>{surpriseIdeas[surpriseIndex].title}</h3><p>{surpriseIdeas[surpriseIndex].prompt}</p></div></div>{surpriseIdeas[surpriseIndex].answer&&<div className="trivia-reveal">{showSurpriseAnswer?<><p><strong>Answer:</strong> {surpriseIdeas[surpriseIndex].answer}</p><button className="fun-text-action" onClick={()=>setShowSurpriseAnswer(false)}>Hide answer</button></>:<button className="fun-action secondary" aria-expanded="false" onClick={()=>setShowSurpriseAnswer(true)}>💡 Reveal answer</button>}</div>}<div className="daily-footer"><span>One little moment can make everyone smile.</span><button className="fun-action secondary" onClick={()=>{setSurpriseIndex((surpriseIndex+1)%surpriseIdeas.length);setShowSurpriseAnswer(false)}}><Sparkles size={15}/> Another idea</button></div></section>
      <section className={`fun-card kindness-card ${pane('badges')}`}><div className="fun-card-title"><div className="fun-panel-icon kindness-icon"><Heart size={18}/></div><div><h2>Kindness badges</h2><p>Celebrate the wonderful ways students show up.</p></div></div><label className="fun-label" htmlFor="badge-student">Choose a student</label><select id="badge-student" className="fun-input" value={badgeStudent} onChange={e=>setBadgeStudent(e.target.value)}>{students.map(s=><option key={s.id} value={s.id}>{displayStudentName(s.name)}</option>)}</select><div className="kindness-badge-grid">{kindnessBadges.map(([emoji,name])=>{const has=Boolean(selectedStudent&&(awarded[selectedStudent.id]||[]).includes(name));return <button key={name} className={`kindness-badge ${has?'awarded':''}`} disabled={!students.length||has} onClick={()=>awardBadge(name)}><span>{emoji}</span><strong>{name}</strong>{has?<small>Earned!</small>:<small>Give badge</small>}</button>})}</div><div className="earned-badges"><strong>Classroom badge shelf</strong><button className="fun-text-action" onClick={()=>setShowAllBadges(!showAllBadges)}>{showAllBadges?'Hide':'See badges'}</button></div>{showAllBadges&&<div className="badge-shelf">{students.flatMap(student=>(awarded[student.id]||[]).map(badge=><span key={`${student.id}-${badge}`} title={`${displayStudentName(student.name)}: ${badge}`}>{kindnessBadges.find(([,name])=>name===badge)?.[0]} {displayStudentName(student.name)}<small>{badge}</small></span>)).length?students.flatMap(student=>(awarded[student.id]||[]).map(badge=><span key={`${student.id}-${badge}`}>{kindnessBadges.find(([,name])=>name===badge)?.[0]} <strong>{displayStudentName(student.name)}</strong><small>{badge}</small></span>)):<p>Badges will sparkle here as you award them.</p>}</div>}</section>
      <section className={`fun-card reward-vote-card ${pane('vote')}`}><div className="fun-card-title"><div className="fun-panel-icon vote-icon"><Trophy size={18}/></div><div><h2>Pick our class reward</h2><p>One vote per student. Change a vote any time.</p></div></div>{students.length&&prizes.length?<><label className="fun-label" htmlFor="vote-student">Voting as</label><select id="vote-student" className="fun-input" value={voteStudent} onChange={e=>setVoteStudent(e.target.value)}>{students.map(s=><option key={s.id} value={s.id}>{displayStudentName(s.name)}</option>)}</select><div className="reward-vote-list">{prizes.map(prize=><button key={prize} className={`reward-vote-option ${votes[voteStudent]===prize?'voted':''}`} onClick={()=>castVote(prize)}><span>🎁</span><strong>{prize}</strong><small>{voteCounts[prize]||0} {voteCounts[prize]===1?'vote':'votes'}</small>{votes[voteStudent]===prize&&<Check size={16}/>}</button>)}</div><p className="vote-result"><Star size={15}/> Class favorite: <strong>{prizes.reduce((best,current)=>(voteCounts[current]||0)>(voteCounts[best]||0)?current:best,prizes[0])}</strong></p></>:<div className="fun-empty">Add students and teacher-approved rewards to start a class vote.</div>}</section>
      <BookPickerCard classroomId={classroomId} classroom={classroom} active={tool==='book'} presentIds={presentIds} studentCount={students.length} onRollCall={onRollCall}/><section className={`fun-card mascot-card ${pane('mascot')}`}><div className="fun-card-title"><div className="fun-panel-icon mascot-icon"><Sparkles size={18}/></div><div><h2>Our classroom mascot</h2><p>A little friend to cheer on your team.</p></div></div><div className="mascot-preview"><span><MascotFace value={mascot.emoji}/></span><div><strong>{mascot.name}</strong><small>Official {classroom} cheerleader</small></div><i>✨</i></div><label className="fun-label" htmlFor="mascot-name">Mascot name</label><input id="mascot-name" className="fun-input" value={mascotName} maxLength={24} onChange={e=>setMascotName(e.target.value)}/><div className="mascot-choices" aria-label="Choose mascot emoji">{mascotChoices.map(emoji=><button key={emoji} className={mascot.emoji===emoji?'selected':''} aria-label={`Choose ${emoji} mascot`} onClick={()=>update({...data,mascots:{...data.mascots,[classroomId]:{emoji,name:mascotName||mascot.name}}})}>{emoji}</button>)}{mascotPictures.map(p=><button key={p.id} className={mascot.emoji===p.id?'selected':''} aria-label={`Choose ${p.name} mascot`} onClick={()=>{setMascotName(p.name);update({...data,mascots:{...data.mascots,[classroomId]:{emoji:p.id,name:p.name}}});}}><MascotFace value={p.id}/></button>)}</div><button className="fun-action secondary" onClick={saveMascot}><Check size={16}/> Save mascot</button></section>
      <section className={`fun-card certificate-card ${pane('certificate')}`}><div className="fun-card-title"><div className="fun-panel-icon certificate-icon"><Award size={18}/></div><div><h2>Champs certificate</h2><p>Print a little reminder of a big effort.</p></div></div><div className="certificate-preview"><span>🏅</span><div><small>AWARD A LITTLE BRILLIANCE</small><strong>{displayStudentName(candidate?.name||students[0]?.name||'Your superstar')}</strong><em>is a wonderful classroom champ!</em></div><Sparkles size={18}/></div><label className="fun-label" htmlFor="certificate-student">Choose a student</label><select id="certificate-student" className="fun-input" value={candidate?.id||students[0]?.id||''} onChange={e=>setCandidate(students.find(s=>s.id===e.target.value)||null)}>{students.map(s=><option key={s.id} value={s.id}>{displayStudentName(s.name)}</option>)}</select><button className="fun-action primary full" disabled={!students.length} onClick={()=>setCertificate(students.find(s=>s.id===(candidate?.id||students[0]?.id))||null)}><Printer size={16}/> Preview &amp; print certificate</button></section>
    </div>
    <section className={`fun-card timer-panel ${pane('timer')}`}>{timerContent}</section>
    <section className="fun-preferences"><div><BellRing size={18}/><span><strong>Celebration style</strong><small>Keep classroom celebrations comfortable for your learners.</small></span></div><label className="celebration-sound-choice">Cheer<select value={data.celebrationSound} onChange={e=>update({...data,celebrationSound:e.target.value as LocalData['celebrationSound']})}><option value="gentle">Gentle chime</option><option value="applause">Applause</option><option value="silent">Silent</option></select></label><label><input type="checkbox" checked={data.celebrationConfetti} onChange={e=>update({...data,celebrationConfetti:e.target.checked})}/> Confetti</label></section>
    {timerFull&&<div className="classroom-timer-fullscreen" role="dialog" aria-modal="true" aria-label="Full-screen classroom activity timer"><button className="timer-exit" onClick={()=>setTimerFull(false)} aria-label="Close full-screen timer"><X size={22}/><span>Exit timer</span></button><div className="timer-full-mascot"><MascotFace value={mascot.emoji}/></div><p className="timer-full-kicker">{classroom.toUpperCase()} · FOCUS TIME</p><h1>{activity||'Classroom activity'}</h1>{timerEffect!=='ring'&&<TimerStage effect={timerEffect} remaining={remaining} duration={duration} running={running} clock={clock} size="full"/>}<div className={`timer-full-ring${timerEffect==='ring'?'':' has-effect'}`} style={{'--timer-progress':`${ringProgress*100}%`} as React.CSSProperties}><span>{clock}</span><small>{remaining===0?'Beautiful work!':running?'Take your time and shine':'Ready when you are'}</small></div><div className="timer-full-controls"><button onClick={running?()=>setRunning(false):startTimer}>{running?<><Pause/> Pause</>:<><Play/> {remaining===0?'Start again':'Start'}</>}</button><button onClick={resetTimer}><RotateCcw/> Reset</button></div><div className="timer-full-effects">{effectPicker}</div><div className="timer-full-presets">{timerPresets.map(minutes=><button key={minutes} className={duration===Math.round(minutes*60)?'chosen':''} disabled={running} onClick={()=>setPreset(minutes)}>{presetLabel(minutes)}</button>)}</div><p className="timer-full-foot">A calm moment to do your best ✦</p></div>}
    {goalCelebration&&<div className="goal-celebration-overlay" role="dialog" aria-modal="true" aria-label="Class goal celebration"><div className="goal-celebration-card"><button onClick={()=>setGoalCelebration(false)} aria-label="Close class celebration"><X size={21}/></button><span>🎊</span><small>WE DID IT, {classroom.toUpperCase()}!</small><h2>Every star was a team effort!</h2><p>You reached your shared goal with {earned} stars. Give your whole classroom a huge cheer!</p><div>👏　⭐　🎉　🌈　🎉　⭐　👏</div></div></div>}
    {certificate&&<div className="certificate-modal"><button className="certificate-close" onClick={()=>setCertificate(null)} aria-label="Close certificate"><X size={20}/></button><article className="certificate-print"><span className="certificate-stars">✦　✿　✦</span><small>EZGILI CHAMPS PRESENTS</small><h2>Superstar Certificate</h2><p>This certificate celebrates</p><strong>{displayStudentName(certificate.name)}</strong><p>for bringing kindness, courage, and wonderful effort to</p><b>{classroom}</b><div className="certificate-medal">{certificate.avatar} ⭐</div><footer><span>{new Date().toLocaleDateString()}</span><span>Keep learning. Keep shining!</span></footer></article><button className="fun-action primary certificate-print-button" onClick={()=>window.print()}><Printer size={17}/> Print certificate</button></div>}
  </div>;
}
