'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { Award, BadgeCheck, BellRing, Check, ChevronDown, Clock3, Gift, Heart, Pause, Play, Printer, RotateCcw, Sparkles, Star, Timer, Trophy, Users, X } from 'lucide-react';

type FunStudent = { id: string; name: string; avatar: string };
type FunProps = { classroomId: string; classroom: string; students: FunStudent[]; prizes: string[]; earned: number };
const goalKey=(id:string)=>`ezgili-class-goal-${id}`;
const surpriseIdeas=[['🕺','Movement minute','Stretch tall like a giraffe, then wiggle like a jellyfish!'],['🎨','Tiny art challenge','Draw a happy monster using only three shapes.'],['🧠','Brain break riddle','What has a face and two hands but no arms or legs? A clock!'],['💛','Kindness mission','Give someone a specific compliment about their effort.'],['🎤','Silly speaking prompt','If your pencil could talk, what would it say today?'],['🐾','Animal stretch','Move like a cat, a flamingo, and a sleepy bear.'],['🌈','Gratitude sparkle','Name one small thing that made you smile this week.']];
const kindnessBadges=[['💛','Kind heart'],['💪','Brave try'],['🤝','Helpful teammate'],['🎤','Bold speaker'],['🌱','Growth mindset'],['✨','Super effort']];
const mascotChoices=['🦊','🦁','🐼','🐸','🦄','🐬','🦉','🐢','🐯','🐙','🐻','🦋'];
const timerPresets=[1,3,5,10,15,20];
type LocalData={goals:Record<string,number>;mascots:Record<string,{emoji:string;name:string}>;badges:Record<string,Record<string,string[]>>;votes:Record<string,Record<string,string>>;celebrationSound:'applause'|'gentle'|'silent';celebrationConfetti:boolean};
const defaultData:LocalData={goals:{},mascots:{},badges:{},votes:{},celebrationSound:'applause',celebrationConfetti:true};
function saveLocal(data:LocalData){try{localStorage.setItem('ezgili-classroom-fun',JSON.stringify(data));window.dispatchEvent(new Event('ezgili-classroom-fun-updated'));}catch{}}
function getLocal():LocalData{try{const saved=JSON.parse(localStorage.getItem('ezgili-classroom-fun')||'{}');return {...defaultData,...saved,goals:saved.goals||{},mascots:saved.mascots||{},badges:saved.badges||{},votes:saved.votes||{}};}catch{return defaultData;}}
export function ClassGoalMeter({classroomId,earned}:{classroomId:string;earned:number}){
  const [goal,setGoal]=useState(20);
  useEffect(()=>{const read=()=>{try{const data=getLocal();setGoal(Number(data.goals[classroomId])||20);}catch{setGoal(20);}};read();window.addEventListener('ezgili-classroom-fun-updated',read);return()=>window.removeEventListener('ezgili-classroom-fun-updated',read);},[classroomId]);
  if(!classroomId)return null;
  const progress=Math.min(100,Math.round(earned/Math.max(goal,1)*100));
  return <section className="fun-goal-strip"><div className="fun-goal-icon">🌈</div><div className="fun-goal-copy"><strong>Our class goal</strong><span>{earned} of {goal} stars · {progress>=100?'We did it!':'Every little effort counts'}</span><div className="fun-goal-track"><i style={{width:`${progress}%`}}/></div></div><span className="fun-goal-percent">{progress}%</span></section>;
}
export default function ClassroomFun({classroomId,classroom,students,prizes,earned}:FunProps){
  const [data,setData]=useState<LocalData>(defaultData);
  const [candidate,setCandidate]=useState<FunStudent|null>(null);
  const [picking,setPicking]=useState(false);
  const pickRef=useRef<ReturnType<typeof setTimeout>|null>(null);
  const [badgeStudent,setBadgeStudent]=useState('');
  const [voteStudent,setVoteStudent]=useState('');
  const [customGoal,setCustomGoal]=useState('');
  const [mascotName,setMascotName]=useState('');
  const [certificate,setCertificate]=useState<FunStudent|null>(null);
  const [goalCelebration,setGoalCelebration]=useState(false);
  const [duration,setDuration]=useState(300);
  const [remaining,setRemaining]=useState(300);
  const [running,setRunning]=useState(false);
  const [timerFull,setTimerFull]=useState(false);
  const [activity,setActivity]=useState('Quiet reading');
  const [surpriseIndex,setSurpriseIndex]=useState(0);
  const [showAllBadges,setShowAllBadges]=useState(false);
  const mascot=data.mascots[classroomId]||{emoji:'🦊',name:'Champs'};
  const votes=data.votes[classroomId]||{};
  const awarded=data.badges[classroomId]||{};
  const goal=Number(data.goals[classroomId])||20;
  const progress=Math.min(100,Math.round(earned/Math.max(goal,1)*100));
  const selectedStudent=students.find(s=>s.id===badgeStudent);
  const selectedVoter=students.find(s=>s.id===voteStudent);
  const voteCounts=useMemo(()=>Object.values(votes).reduce<Record<string,number>>((counts,prize)=>({...counts,[prize]:(counts[prize]||0)+1}),{}),[votes]);
  useEffect(()=>{const initial=getLocal();setData(initial);setCustomGoal(String(initial.goals[classroomId]||20));setMascotName(initial.mascots[classroomId]?.name||'Champs');setBadgeStudent(students[0]?.id||'');setVoteStudent(students[0]?.id||'');const day=new Date();setSurpriseIndex((Math.floor((Date.UTC(day.getFullYear(),day.getMonth(),day.getDate())-Date.UTC(day.getFullYear(),0,0))/86400000))%surpriseIdeas.length);},[classroomId]);
  useEffect(()=>{if(students.length&&!students.some(student=>student.id===badgeStudent))setBadgeStudent(students[0].id);if(students.length&&!students.some(student=>student.id===voteStudent))setVoteStudent(students[0].id);},[students,badgeStudent,voteStudent]);
  useEffect(()=>{if(!running)return;const interval=setInterval(()=>setRemaining(current=>{if(current<=1){setRunning(false);return 0;}return current-1;}),1000);return()=>clearInterval(interval);},[running]);
  useEffect(()=>()=>{if(pickRef.current)clearTimeout(pickRef.current);},[]);
  useEffect(()=>{if(!timerFull)return;const onKey=(event:KeyboardEvent)=>{if(event.key==='Escape')setTimerFull(false);};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);},[timerFull]);
  const update=(next:LocalData)=>{setData(next);saveLocal(next);};
  const startPicker=()=>{if(!students.length||picking)return;setPicking(true);let turns=0;const spin=()=>{const next=students[Math.floor(Math.random()*students.length)];setCandidate(next);turns++;if(turns<18)pickRef.current=setTimeout(spin,65+turns*12);else setPicking(false);};spin();};
  const adjustGoal=()=>{const value=Math.max(1,Math.min(100000,Number(customGoal)||20));setCustomGoal(String(value));update({...data,goals:{...data.goals,[classroomId]:value}});};
  const saveMascot=()=>update({...data,mascots:{...data.mascots,[classroomId]:{...mascot,name:mascotName.trim()||'Champs'}}});
  const awardBadge=(badge:string)=>{if(!selectedStudent)return;const list=awarded[selectedStudent.id]||[];if(list.includes(badge))return;update({...data,badges:{...data.badges,[classroomId]:{...awarded,[selectedStudent.id]:[...list,badge]}}});};
  const castVote=(prize:string)=>{if(!selectedVoter)return;update({...data,votes:{...data.votes,[classroomId]:{...votes,[selectedVoter.id]:prize}}});};
  const startTimer=()=>{if(remaining===0)setRemaining(duration);setRunning(true);};
  const setPreset=(minutes:number)=>{const seconds=minutes*60;setDuration(seconds);setRemaining(seconds);setRunning(false);};
  const resetTimer=()=>{setRunning(false);setRemaining(duration);};
  const clock=`${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}`;
  const ringProgress=1-remaining/Math.max(1,duration);
  const timerContent=<><div className="fun-timer-head"><div className="fun-panel-icon timer-icon"><Timer size={19}/></div><div><h2>Activity timer</h2><p>A lovely little focus session for {classroom}.</p></div><button className="fun-expand" onClick={()=>setTimerFull(true)} aria-label="Open full-screen timer" title="Full screen"><span>⛶</span></button></div><label className="fun-label" htmlFor="activity-name">What are we doing?</label><input id="activity-name" className="fun-input" value={activity} maxLength={45} onChange={e=>setActivity(e.target.value)} placeholder="e.g. Quiet reading"/><div className="fun-presets">{timerPresets.map(minutes=><button key={minutes} className={duration===minutes*60?'chosen':''} onClick={()=>setPreset(minutes)} disabled={running}>{minutes} min</button>)}</div><div className="fun-timer-clock"><div className="fun-clock-ring" style={{'--timer-progress':`${ringProgress*100}%`} as React.CSSProperties}><Clock3 size={21}/><strong>{clock}</strong><span>{remaining===0?'Time to celebrate!':running?'You’ve got this!':'Ready when you are'}</span></div></div><div className="fun-timer-actions"><button className="fun-action primary" onClick={running?()=>setRunning(false):startTimer}>{running?<><Pause size={17}/> Pause</>:<><Play size={17}/> {remaining===0?'Start again':'Start timer'}</>}</button><button className="fun-action secondary" onClick={resetTimer}><RotateCcw size={16}/> Reset</button><button className="fun-action secondary" onClick={()=>setTimerFull(true)}>Full screen</button></div>{remaining===0&&<div className="fun-timer-finished" role="status">🌟 Wonderful focus, {classroom}! Take a stretch break.</div>}</>;
  return <div className="classroom-fun-page">
    <div className="fun-page-hero"><div><p className="fun-eyebrow">PLAY, FOCUS &amp; SHINE</p><h1>Let’s make learning <em>an adventure!</em></h1><p>Little surprises, big cheers, and a few helpful classroom tools.</p></div><div className="fun-mascot-bubble" aria-hidden="true">{mascot.emoji}<i>✦</i></div></div>
    <section className="fun-goal-card"><div className="fun-goal-top"><span className="fun-feature-emoji">🌈</span><div><span className="fun-kicker">TEAMWORK MAKES THE DREAM WORK</span><h2>{progress>=100?'Our class did it!':`Our ${classroom} class goal`}</h2><p>{progress>=100?'High fives all around. Pick a new goal to keep the joy going!':'Every effort adds another star to our shared goal.'}</p></div><span className="fun-goal-medal">{progress>=100?'🏆':'⭐'}</span></div><div className="fun-goal-track large"><i style={{width:`${progress}%`}}/></div><div className="fun-goal-bottom"><strong>{earned} <small>of {goal} stars</small></strong><label>Goal <input aria-label="Set class star goal" type="number" min="1" max="100000" value={customGoal} onChange={e=>setCustomGoal(e.target.value)} onBlur={adjustGoal} onKeyDown={e=>{if(e.key==='Enter')adjustGoal()}}/></label></div>{progress>=100&&<button className="fun-action primary goal-celebrate-button" onClick={()=>setGoalCelebration(true)}>🎉 Celebrate our class goal!</button>}</section>
    <div className="fun-feature-grid">
      <section className="fun-card picker-card"><div className="fun-card-title"><div className="fun-panel-icon picker-icon"><Users size={18}/></div><div><h2>Who’s up next?</h2><p>Let the Champs picker choose fairly.</p></div></div><div className={`picker-stage ${picking?'is-picking':''}`}><span className="picker-confetti" aria-hidden="true">✦　✧　✿</span><span className="picker-avatar">{candidate?.avatar||'🎁'}</span><strong>{candidate?.name||(students.length?'Ready for a surprise?':'Add students to start!')}</strong><small>{picking?'Picking a lucky learner…':candidate?'You’re our superstar!':'Everyone has an equal chance.'}</small></div><button className="fun-action primary full" disabled={!students.length||picking} onClick={startPicker}><Sparkles size={17}/>{picking?'Picking…':'Pick a student!'}</button>{candidate&&!picking&&<button className="fun-text-action" onClick={()=>setCertificate(candidate)}>Make a certificate for {candidate.name}</button>}</section>
      <section className="fun-card daily-card"><div className="fun-card-title"><div className="fun-panel-icon daily-icon"><Gift size={18}/></div><div><h2>Today’s surprise</h2><p>A tiny idea for a brighter day.</p></div></div><div className="daily-surprise"><span>{surpriseIdeas[surpriseIndex][0]}</span><div><small>CLASSROOM CHALLENGE</small><h3>{surpriseIdeas[surpriseIndex][1]}</h3><p>{surpriseIdeas[surpriseIndex][2]}</p></div></div><div className="daily-footer"><span>One little moment can make everyone smile.</span><button className="fun-action secondary" onClick={()=>setSurpriseIndex((surpriseIndex+1)%surpriseIdeas.length)}><Sparkles size={15}/> Another idea</button></div></section>
      <section className="fun-card kindness-card"><div className="fun-card-title"><div className="fun-panel-icon kindness-icon"><Heart size={18}/></div><div><h2>Kindness badges</h2><p>Celebrate the wonderful ways students show up.</p></div></div><label className="fun-label" htmlFor="badge-student">Choose a student</label><select id="badge-student" className="fun-input" value={badgeStudent} onChange={e=>setBadgeStudent(e.target.value)}>{students.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><div className="kindness-badge-grid">{kindnessBadges.map(([emoji,name])=>{const has=Boolean(selectedStudent&&(awarded[selectedStudent.id]||[]).includes(name));return <button key={name} className={`kindness-badge ${has?'awarded':''}`} disabled={!students.length||has} onClick={()=>awardBadge(name)}><span>{emoji}</span><strong>{name}</strong>{has?<small>Earned!</small>:<small>Give badge</small>}</button>})}</div><div className="earned-badges"><strong>Classroom badge shelf</strong><button className="fun-text-action" onClick={()=>setShowAllBadges(!showAllBadges)}>{showAllBadges?'Hide':'See badges'}</button></div>{showAllBadges&&<div className="badge-shelf">{students.flatMap(student=>(awarded[student.id]||[]).map(badge=><span key={`${student.id}-${badge}`} title={`${student.name}: ${badge}`}>{kindnessBadges.find(([,name])=>name===badge)?.[0]} {student.name}<small>{badge}</small></span>)).length?students.flatMap(student=>(awarded[student.id]||[]).map(badge=><span key={`${student.id}-${badge}`}>{kindnessBadges.find(([,name])=>name===badge)?.[0]} <strong>{student.name}</strong><small>{badge}</small></span>)):<p>Badges will sparkle here as you award them.</p>}</div>}</section>
      <section className="fun-card reward-vote-card"><div className="fun-card-title"><div className="fun-panel-icon vote-icon"><Trophy size={18}/></div><div><h2>Pick our class reward</h2><p>One vote per student. Change a vote any time.</p></div></div>{students.length&&prizes.length?<><label className="fun-label" htmlFor="vote-student">Voting as</label><select id="vote-student" className="fun-input" value={voteStudent} onChange={e=>setVoteStudent(e.target.value)}>{students.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><div className="reward-vote-list">{prizes.map(prize=><button key={prize} className={`reward-vote-option ${votes[voteStudent]===prize?'voted':''}`} onClick={()=>castVote(prize)}><span>🎁</span><strong>{prize}</strong><small>{voteCounts[prize]||0} {voteCounts[prize]===1?'vote':'votes'}</small>{votes[voteStudent]===prize&&<Check size={16}/>}</button>)}</div><p className="vote-result"><Star size={15}/> Class favorite: <strong>{prizes.reduce((best,current)=>(voteCounts[current]||0)>(voteCounts[best]||0)?current:best,prizes[0])}</strong></p></>:<div className="fun-empty">Add students and teacher-approved rewards to start a class vote.</div>}</section>
      <section className="fun-card mascot-card"><div className="fun-card-title"><div className="fun-panel-icon mascot-icon"><Sparkles size={18}/></div><div><h2>Our classroom mascot</h2><p>A little friend to cheer on your team.</p></div></div><div className="mascot-preview"><span>{mascot.emoji}</span><div><strong>{mascot.name}</strong><small>Official {classroom} cheerleader</small></div><i>✨</i></div><label className="fun-label" htmlFor="mascot-name">Mascot name</label><input id="mascot-name" className="fun-input" value={mascotName} maxLength={24} onChange={e=>setMascotName(e.target.value)}/><div className="mascot-choices" aria-label="Choose mascot emoji">{mascotChoices.map(emoji=><button key={emoji} className={mascot.emoji===emoji?'selected':''} aria-label={`Choose ${emoji} mascot`} onClick={()=>update({...data,mascots:{...data.mascots,[classroomId]:{emoji,name:mascotName||mascot.name}}})}>{emoji}</button>)}</div><button className="fun-action secondary" onClick={saveMascot}><Check size={16}/> Save mascot</button></section>
      <section className="fun-card certificate-card"><div className="fun-card-title"><div className="fun-panel-icon certificate-icon"><Award size={18}/></div><div><h2>Champs certificate</h2><p>Print a little reminder of a big effort.</p></div></div><div className="certificate-preview"><span>🏅</span><div><small>AWARD A LITTLE BRILLIANCE</small><strong>{candidate?.name||students[0]?.name||'Your superstar'}</strong><em>is a wonderful classroom champ!</em></div><Sparkles size={18}/></div><label className="fun-label" htmlFor="certificate-student">Choose a student</label><select id="certificate-student" className="fun-input" value={candidate?.id||students[0]?.id||''} onChange={e=>setCandidate(students.find(s=>s.id===e.target.value)||null)}>{students.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><button className="fun-action primary full" disabled={!students.length} onClick={()=>setCertificate(students.find(s=>s.id===(candidate?.id||students[0]?.id))||null)}><Printer size={16}/> Preview &amp; print certificate</button></section>
    </div>
    <section className="fun-card timer-panel">{timerContent}</section>
    <section className="fun-preferences"><div><BellRing size={18}/><span><strong>Celebration style</strong><small>Keep classroom celebrations comfortable for your learners.</small></span></div><label className="celebration-sound-choice">Cheer<select value={data.celebrationSound} onChange={e=>update({...data,celebrationSound:e.target.value as LocalData['celebrationSound']})}><option value="gentle">Gentle chime</option><option value="applause">Applause</option><option value="silent">Silent</option></select></label><label><input type="checkbox" checked={data.celebrationConfetti} onChange={e=>update({...data,celebrationConfetti:e.target.checked})}/> Confetti</label></section>
    {timerFull&&<div className="classroom-timer-fullscreen" role="dialog" aria-modal="true" aria-label="Full-screen classroom activity timer"><button className="timer-exit" onClick={()=>setTimerFull(false)} aria-label="Close full-screen timer"><X size={22}/><span>Exit timer</span></button><div className="timer-full-mascot">{mascot.emoji}</div><p className="timer-full-kicker">{classroom.toUpperCase()} · FOCUS TIME</p><h1>{activity||'Classroom activity'}</h1><div className="timer-full-ring" style={{'--timer-progress':`${ringProgress*100}%`} as React.CSSProperties}><span>{clock}</span><small>{remaining===0?'Beautiful work!':running?'Take your time and shine':'Ready when you are'}</small></div><div className="timer-full-controls"><button onClick={running?()=>setRunning(false):startTimer}>{running?<><Pause/> Pause</>:<><Play/> {remaining===0?'Start again':'Start'}</>}</button><button onClick={resetTimer}><RotateCcw/> Reset</button></div><div className="timer-full-presets">{timerPresets.map(minutes=><button key={minutes} className={duration===minutes*60?'chosen':''} disabled={running} onClick={()=>setPreset(minutes)}>{minutes} min</button>)}</div><p className="timer-full-foot">A calm moment to do your best ✦</p></div>}
    {goalCelebration&&<div className="goal-celebration-overlay" role="dialog" aria-modal="true" aria-label="Class goal celebration"><div className="goal-celebration-card"><button onClick={()=>setGoalCelebration(false)} aria-label="Close class celebration"><X size={21}/></button><span>🎊</span><small>WE DID IT, {classroom.toUpperCase()}!</small><h2>Every star was a team effort!</h2><p>You reached your shared goal with {earned} stars. Give your whole classroom a huge cheer!</p><div>👏　⭐　🎉　🌈　🎉　⭐　👏</div></div></div>}
    {certificate&&<div className="certificate-modal"><button className="certificate-close" onClick={()=>setCertificate(null)} aria-label="Close certificate"><X size={20}/></button><article className="certificate-print"><span className="certificate-stars">✦　✿　✦</span><small>EZGILI CHAMPS PRESENTS</small><h2>Superstar Certificate</h2><p>This certificate celebrates</p><strong>{certificate.name}</strong><p>for bringing kindness, courage, and wonderful effort to</p><b>{classroom}</b><div className="certificate-medal">{certificate.avatar} ⭐</div><footer><span>{new Date().toLocaleDateString()}</span><span>Keep learning. Keep shining!</span></footer></article><button className="fun-action primary certificate-print-button" onClick={()=>window.print()}><Printer size={17}/> Print certificate</button></div>}
  </div>;
}
