'use client';

import { useEffect, useMemo, useRef, useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { archiveClassroom, archiveGroup, archiveStudent, createClassroom, createGroup, createStudent, createPrize, drawReward, getPeriodReport, saveBehaviorRecord, setPrizeActive, signOut, updateTutorSettings } from './actions';
import { Activity, Archive, ArrowDownRight, ArrowRight, Award, BarChart3, Bell, BookOpen, CalendarDays, Check, CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, CircleHelp, ClipboardCheck, Clock3, Coffee, Gift, GraduationCap, Heart, Home, Leaf, LogOut, Menu, MoreHorizontal, Plus, Search, Settings, ShieldCheck, Smile, Sparkles, Star, Trophy, Users, X } from 'lucide-react';

const criteria = ['Homework completed', 'Class participation', 'Effort in speaking', 'Project completed', 'Classwise readiness', 'Followed speaking-day rules'];
const seedStudents = [
  { id: 1, name: 'Ava Johnson', avatar: '🦊', color: 'peach', checks: [true,true,true,false,true,false], streak: 4 },
  { id: 2, name: 'Noah Williams', avatar: '🐻', color: 'blue', checks: [true,true,false,true,true,true], streak: 2 },
  { id: 3, name: 'Mia Chen', avatar: '🐼', color: 'lilac', checks: [true,false,true,true,false,true], streak: 5 },
  { id: 4, name: 'Leo Martinez', avatar: '🦁', color: 'yellow', checks: [false,true,true,true,true,false], streak: 1 },
  { id: 5, name: 'Amara Okafor', avatar: '🐸', color: 'mint', checks: [true,true,true,true,false,true], streak: 3 },
  { id: 6, name: 'Ethan Brown', avatar: '🐯', color: 'peach', checks: [true,false,false,true,true,true], streak: 2 },
];
const starterPrizes = ['Choose the read-aloud book','Pick the warm-up game','Be the line leader','10 minutes of drawing time','A colorful sticker','Choose a classroom song'];
type Student = typeof seedStudents[number];
type Draw = { name:string; prize:string; avatar:string; at:string };

type InitialData = Awaited<ReturnType<typeof import('./actions').getInitialData>>;
export default function HomePage({initialData}:{initialData:InitialData}) {
  const router=useRouter();
  const [pending,startTransition]=useTransition();
  const drawKey=useRef<string|null>(null);
  const saves=useRef<Map<number,Promise<unknown>>>(new Map());
  const [reportData,setReportData]=useState<{from:string;to:string;rows:Array<Record<string,unknown>>}|null>(null);
  const groups=initialData.groups as Array<{id:string;name:string;classroom_name:string}>;
  const classroomCards=(initialData.classrooms as Array<{id:string;name:string}>).map((c,i)=>({id:c.id,name:c.name,room:`${groups.filter(g=>g.classroom_name===c.name).length} active groups`,emoji:['🌻','🎨','📚'][i%3],groups:groups.filter(g=>g.classroom_name===c.name).map(g=>({id:g.id,name:g.name})),tone:i%2?'creative':'sunflower'}));
  const [groupId,setGroupId]=useState(groups[0]?.id||'');
  const [tab,setTab] = useState('Today');
  const [students,setStudents] = useState<Student[]>(()=>((initialData.students as Array<{id:string;display_name:string;avatar_key:string;group_id:string;criteria:Record<string,boolean>|null}>).filter(s=>s.group_id===groups[0]?.id).map((s,i)=>({id:s.id as unknown as number,name:s.display_name,avatar:({fox:'🦊',bear:'🐻',panda:'🐼',lion:'🦁',frog:'🐸',tiger:'🐯',koala:'🐨',unicorn:'🦄',penguin:'🐧',octopus:'🐙'} as Record<string,string>)[s.avatar_key]||'🙂',color:['peach','blue','lilac','yellow','mint'][i%5],checks:s.criteria?criteria.map((_,j)=>Boolean(s.criteria?.[['homework_complete','class_participation','speaking_effort','project_complete','class_readiness','speaking_day_rules'][j]])):[false,false,false,false,false,false],streak:0}))));
  const [prizes,setPrizes] = useState<string[]>((initialData.prizes as Array<{name:string;active:boolean}>).filter(p=>p.active).map(p=>p.name));
  const [draws,setDraws] = useState<Draw[]>((initialData.recentDraws as Array<{student:string;prize:string;avatar_key:string;drawn_at:string}>).map(d=>({name:d.student,prize:d.prize,avatar:'🎉',at:new Date(d.drawn_at).toLocaleDateString()})));
  const [group,setGroup] = useState(groups[0]?`${groups[0].classroom_name} · ${groups[0].name}`:'Choose a group');
  const date=initialData.today;
  const [period,setPeriod] = useState('This week');
  const [modal,setModal] = useState('');
  const [query,setQuery] = useState('');
  const [draft,setDraft] = useState('');
  const [winner,setWinner] = useState<Draw|null>(null);
  const [spinning,setSpinning] = useState(false);
  const [sidebar,setSidebar] = useState(true);
  const [toast,setToast] = useState('');
  const [displayName,setDisplayName]=useState(String(initialData.tutor.display_name));
  const [timezone,setTimezone]=useState(String(initialData.tutor.timezone));
  const [currentPassword,setCurrentPassword]=useState('');
  const [newPassword,setNewPassword]=useState('');
  const [drawStudentId,setDrawStudentId]=useState('');
  const total = (s:Student)=>s.checks.filter(Boolean).length;
  const earned=students.reduce((n,s)=>n+total(s),0), possible=students.length*criteria.length;

  useEffect(()=>{ const found=groups.find(g=>g.id===groupId); if(found){setGroup(`${found.classroom_name} · ${found.name}`);const dbStudents=(initialData.students as Array<{id:string;display_name:string;avatar_key:string;group_id:string;criteria:Record<string,boolean>|null}>).filter(s=>s.group_id===groupId);setStudents(dbStudents.map((s,i)=>({id:s.id as unknown as number,name:s.display_name,avatar:({fox:'🦊',bear:'🐻',panda:'🐼',lion:'🦁',frog:'🐸',tiger:'🐯',koala:'🐨',unicorn:'🦄',penguin:'🐧',octopus:'🐙'} as Record<string,string>)[s.avatar_key]||'🙂',color:['peach','blue','lilac','yellow','mint'][i%5],checks:s.criteria?criteria.map((_,j)=>Boolean(s.criteria?.[['homework_complete','class_participation','speaking_effort','project_complete','class_readiness','speaking_day_rules'][j]])):[false,false,false,false,false,false],streak:0})));} },[groupId]);
  useEffect(()=>{if(groupId) getPeriodReport(groupId,period==='This month'?'month':'week').then(setReportData).catch(()=>notify('Could not load this report.'));},[groupId,period,earned]);
  const filtered=useMemo(()=>students.filter(s=>s.name.toLowerCase().includes(query.toLowerCase())),[students,query]);
  const notify=(msg:string)=>{setToast(msg);setTimeout(()=>setToast(''),2400)};
  const toggle=(id:number,index:number)=>{const target=students.find(s=>s.id===id); if(!target||!groupId)return;const checks=target.checks.map((c,i)=>i===index?!c:c);setStudents(prev=>prev.map(s=>s.id===id?{...s,checks}:s));startTransition(async()=>{const previous=saves.current.get(id)||Promise.resolve();const next=previous.catch(()=>undefined).then(()=>saveBehaviorRecord(String(id),groupId,initialData.today,Object.fromEntries(['homework_complete','class_participation','speaking_effort','project_complete','class_readiness','speaking_day_rules'].map((k,i)=>[k,checks[i]]))));saves.current.set(id,next);try{await next;notify('Progress saved');}catch{notify('Could not save. Please try again.');}});};
  const addStudent=()=>{const name=draft.trim();if(!name||!groupId)return;startTransition(async()=>{try{const row=await createStudent(groupId,name,['koala','unicorn','penguin','octopus'][Math.floor(Math.random()*4)]);setStudents(prev=>[...prev,{id:row.id as unknown as number,name,avatar:'🐨',color:'mint',checks:[false,false,false,false,false,false],streak:0}]);setDraft('');setModal('');notify(`${name} added to the group`);}catch{notify('Could not add student.');}});};
  const addPrize=()=>{if(!draft.trim())return;startTransition(async()=>{try{await createPrize(draft.trim());setPrizes(prev=>[...prev,draft.trim()]);setDraft('');setModal('');notify('Prize added');}catch{notify('Could not add prize.');}});};
  const deactivatePrize=(prizeName:string)=>{const prize=(initialData.prizes as Array<{id:string;name:string}>).find(p=>p.name===prizeName);if(!prize)return;startTransition(async()=>{try{await setPrizeActive(prize.id,false);setPrizes(prev=>prev.filter(p=>p!==prizeName));notify('Prize deactivated');}catch{notify('Could not update prize.');}});};
  const draw=()=>{if(!groupId){notify('Create a group first');return;}setSpinning(true);drawKey.current??=crypto.randomUUID();const key=drawKey.current;startTransition(async()=>{try{const result=await drawReward({idempotencyKey:key,groupId,studentId:drawStudentId||undefined});drawKey.current=null;setTimeout(()=>{const row=result as {student:string;prize:string;avatar_key:string;drawn_at:string};const display={name:row.student,prize:row.prize,avatar:({fox:'🦊',bear:'🐻',panda:'🐼',lion:'🦁',frog:'🐸',tiger:'🐯',koala:'🐨',unicorn:'🦄',penguin:'🐧',octopus:'🐙'} as Record<string,string>)[row.avatar_key]||'🎉',at:'Just now'};setDraws(prev=>[display,...prev]);setWinner(display);setSpinning(false);},800);}catch(e){setSpinning(false);notify(e instanceof Error?e.message:'Could not draw a reward.');}});};
  const createClass=(value:string)=>{startTransition(async()=>{try{await createClassroom(value);router.refresh();notify('Classroom created');setDraft('');setModal('');}catch{notify('Could not create classroom.');}});};
  const createNewGroup=(value:string)=>{const classroom=(initialData.classrooms as Array<{id:string}>)[0];if(!classroom){notify('Create a classroom first.');return;}startTransition(async()=>{try{await createGroup(classroom.id,value);router.refresh();setDraft('');setModal('');notify('Group created');}catch{notify('Could not create group.');}});};
  const archiveClass=(id:string)=>{if(!window.confirm('Archive this classroom and its groups? Historical records will be kept.'))return;startTransition(async()=>{try{await archiveClassroom(id);router.refresh();notify('Classroom archived');}catch{notify('Could not archive classroom.');}});};
  const archiveThisGroup=(id:string)=>{if(!window.confirm('Archive this group and its active students? Historical records will be kept.'))return;startTransition(async()=>{try{await archiveGroup(id);router.refresh();notify('Group archived');}catch{notify('Could not archive group.');}});};
  const archiveThisStudent=(id:number,name:string)=>{if(!window.confirm(`Archive ${name}? Their historical records will be kept.`))return;startTransition(async()=>{try{await archiveStudent(String(id));setStudents(prev=>prev.filter(s=>s.id!==id));notify('Student archived');}catch{notify('Could not archive student.');}});};
  const saveSettings=()=>startTransition(async()=>{try{const result=await updateTutorSettings({displayName,timezone,currentPassword:currentPassword||undefined,newPassword:newPassword||undefined});setDisplayName(result.displayName);setTimezone(result.timezone);setCurrentPassword('');setNewPassword('');notify('Settings saved');}catch(e){notify(e instanceof Error?e.message:'Could not save settings.');}});
  const nav=[{label:'Today',icon:Home},{label:'Classrooms',icon:GraduationCap},{label:'Reports',icon:BarChart3},{label:'Reward draw',icon:Gift}];
  const chartKeys=['homework_complete','class_participation','speaking_effort','project_complete','class_readiness','speaking_day_rules'];
  const categoryValues=chartKeys.map(key=>reportData?.rows.reduce((sum,row)=>sum+Number(row[key]||0),0)??0);
  const chartBars=categoryValues.map(value=>Math.max(5,value/Math.max(1,...categoryValues)*100));

  return <main className="app-shell">
    <aside className={`sidebar ${sidebar?'':'collapsed'}`}>
      <div className="brand"><div className="brand-mark"><Sparkles size={20}/></div><span>brightsteps</span><button aria-label="Collapse menu" className="icon-btn collapse-btn" onClick={()=>setSidebar(!sidebar)}><ChevronLeft size={17}/></button></div>
      <div className="workspace-label">YOUR CLASSROOM</div>
      <button className="class-switch" onClick={()=>setModal('groups')}><span className="switch-icon"><GraduationCap size={17}/></span><span><strong>Ms. Parker’s class</strong><small>Elementary · Room 04</small></span><ChevronDown size={15}/></button>
      <div className="nav-label">MENU</div><nav>{nav.map(item=><button key={item.label} onClick={()=>setTab(item.label)} className={`nav-item ${tab===item.label?'active':''}`}><item.icon size={18}/><span>{item.label}</span>{item.label==='Reward draw'&&<span className="nav-dot"/>}</button>)}</nav>
      <div className="nav-label groups-label">YOUR GROUPS <button aria-label="Add group" onClick={()=>setModal('groups')}><Plus size={15}/></button></div>
      <div className="group-list">{groups.map((g,i)=><button key={g.id} className={`group-item ${groupId===g.id?'selected':''}`} onClick={()=>setGroupId(g.id)}><span className={`group-dot ${['sun','robin','owl'][i%3]}`}/>{g.name}</button>)}</div>
      <div className="side-bottom"><button className={`nav-item ${tab==='Settings'?'active':''}`} onClick={()=>setTab('Settings')}><Settings size={18}/><span>Settings</span></button><button className="nav-item" onClick={()=>startTransition(async()=>{await signOut();})}><LogOut size={18}/><span>Sign out</span></button><div className="teacher-card"><div className="teacher-avatar">{String(initialData.tutor.display_name).split(' ').map(n=>n[0]).slice(0,2).join('')}</div><div><strong>{String(initialData.tutor.display_name)}</strong><small>Class teacher</small></div><MoreHorizontal size={19}/></div></div>
    </aside>
    <section className="main-area">
      <header className="topbar"><div className="crumb"><span>Classroom</span><ChevronRight size={15}/><strong>{tab==='Today'?'Overview':tab}</strong></div><div className="top-actions"><button aria-label="Help" className="icon-btn"><CircleHelp size={19}/></button><button aria-label="Notifications" className="icon-btn notification"><Bell size={19}/><i/></button><div className="top-divider"/><div className="top-date"><CalendarDays size={17}/><span>{initialData.today}</span></div></div></header>
      {tab==='Today'&&<div className="page-wrap">
        <div className="welcome-row"><div><p className="eyebrow">{initialData.today} <span>✦</span></p><h1>A little progress goes<br className="desktop-break"/> a <em>long</em> way, Sarah.</h1><p className="subhead">Here’s how your classroom is doing today.</p></div><div className="hero-art"><div className="art-sun"/><div className="art-cloud">☁</div><div className="art-book">📚</div><div className="art-flower">✿</div><span className="art-note">Small wins<br/>add up!</span></div></div>
        <div className="toolbar"><div className="group-picker"><span className="picker-icon"><Users size={16}/></span><select value={groupId} onChange={e=>setGroupId(e.target.value)} aria-label="Select group">{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><ChevronDown size={15}/></div><div className="date-picker"><CalendarDays size={16}/><span>{initialData.today}</span></div><button className="outline-btn" onClick={()=>setModal('addStudent')}><Plus size={16}/> Add student</button></div>
        <div className="stats-grid"><div className="stat-card progress-card"><div className="stat-top"><span>Today’s class progress</span><span className="stat-icon teal"><ClipboardCheck size={17}/></span></div><div className="stat-main"><strong>{Math.round(earned/Math.max(possible,1)*100)}<small>%</small></strong><span className="trend positive"><ArrowDownRight size={14}/> Great momentum</span></div><div className="progress-track"><span style={{width:`${Math.round(earned/Math.max(possible,1)*100)}%`}}/></div><small className="stat-caption">{earned} of {possible} possible points earned</small></div><div className="stat-card"><div className="stat-top"><span>Students in group</span><span className="stat-icon purple"><Users size={17}/></span></div><div className="stat-main"><strong>{students.length}</strong><span className="stat-caption">active learners</span></div><div className="mini-avatars">{students.slice(0,5).map(s=><span key={s.id}>{s.avatar}</span>)}<b>+{Math.max(students.length-5,0)}</b></div></div><div className="stat-card"><div className="stat-top"><span>Points this period</span><span className="stat-icon gold"><Star size={17}/></span></div><div className="stat-main"><strong>{(reportData?.rows.reduce((sum,row)=>sum+Number(row.total||0),0)??0)}</strong><span className="trend positive"><ArrowDownRight size={14}/> in selected period</span></div><div className="sparkline">{[19,30,24,40,33,52,41,58,39,63,45,72,57,84,68,95,70,100].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div></div></div>
        <div className="section-heading"><div><h2>Daily check-in <span className="live-badge"><i/> LIVE</span></h2><p>Celebrate the little things that make a big difference.</p></div><button className="text-link" onClick={()=>setTab('Reports')}>View reports <ArrowRight size={16}/></button></div>
        <div className="roster-card"><div className="roster-head"><div className="roster-title"><strong>{group}</strong><span>{students.length} students <i>·</i> {date}</span></div><div className="roster-tools"><div className="searchbox"><Search size={15}/><input placeholder="Find a student" value={query} onChange={e=>setQuery(e.target.value)}/></div><button className="icon-btn subtle" aria-label="Roster options"><MoreHorizontal size={19}/></button></div></div><div className="criteria-head"><span>STUDENT</span>{criteria.map((c,i)=><span key={c} title={c} className="criterion-label"><span className="criterion-index">{i+1}</span>{c}</span>)}<span>POINTS</span></div>
          {filtered.map(s=><div className="student-row" key={s.id}><div className="student-cell"><div className={`student-avatar ${s.color}`}>{s.avatar}</div><div className="student-name"><strong>{s.name}</strong><small>{s.streak>0?<><FlameIcon/> {s.streak} day streak</>:'Just getting started'}</small></div></div>{s.checks.map((checked,i)=><div className="check-cell" key={i}><button aria-label={`${criteria[i]} for ${s.name}`} aria-pressed={checked} className={`check-button ${checked?'checked':''}`} onClick={()=>toggle(s.id,i)}>{checked&&<Check size={14} strokeWidth={3}/>}</button></div>)}<div className="points-cell"><strong>{total(s)}</strong><span>/ 6</span></div></div>)}
          {!filtered.length&&<div className="empty-search">No students match “{query}”.</div>}
          <div className="roster-foot"><span><CheckCircle2 size={15}/> {students.filter(s=>total(s)>0).length} of {students.length} students checked in</span><button onClick={()=>notify('All changes are saved')}>All changes saved <Check size={14}/></button></div>
        </div>
        <div className="bottom-grid"><section className="insight-card"><div className="card-heading"><div><span className="kicker">A LITTLE LOOK BACK</span><h3>Points by criterion</h3></div><select value={period} onChange={e=>setPeriod(e.target.value)}><option>This week</option><option>This month</option></select></div><div className="chart-wrap"><div className="chart-y"><span>60</span><span>40</span><span>20</span><span>0</span></div><div className="chart-area"><div className="grid-lines"><i/><i/><i/><i/></div><div className="bars">{chartBars.map((n,i)=><div className="bar-column" key={i}><span style={{height:`${n}%`}} className={i===13?'today-bar':''}/><small>{['H','P','S','P','R','R'][i]}</small></div>)}</div></div></div><div className="chart-legend"><span><i/> Points earned</span><span className="chart-total">+{(reportData?.rows.reduce((sum,row)=>sum+Number(row.total||0),0)??0)} <small>total points</small></span></div></section>
          <section className="draw-card"><div className="draw-copy"><span className="kicker">A MOMENT TO CELEBRATE</span><h3>Ready for a<br/><em>little surprise?</em></h3><p>Pick a student and let the reward basket decide.</p><button className="primary-btn" onClick={()=>setTab('Reward draw')}>Go to reward draw <ArrowRight size={16}/></button></div><div className="draw-illustration"><div className="spark s1">✦</div><div className="giftbox"><div className="ribbon"/><div className="lid"/></div><div className="spark s2">✧</div><div className="confetti c1"/><div className="confetti c2"/><div className="confetti c3"/></div></section></div>
        <footer className="page-footer"><span>Made for the moments that matter <Heart size={13} fill="currentColor"/></span><span>BrightSteps · Your classroom, one kind act at a time</span></footer>
      </div>}
      {tab==='Reward draw'&&<div className="page-wrap alternate"><p className="eyebrow">A MOMENT TO CELEBRATE</p><h1>Let’s make someone’s <em>day!</em></h1><p className="subhead">A little surprise for a whole lot of effort.</p><div className="draw-page-grid"><section className="draw-setup panel"><div className="panel-title"><div className="panel-icon coral"><Gift size={19}/></div><div><h2>Reward basket</h2><p>One student, one lovely surprise.</p></div></div><label className="field-label">Choose a group</label><select className="field-select" value={groupId} onChange={e=>{setGroupId(e.target.value);setDrawStudentId('')}}>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><label className="field-label">Who’s getting a treat?</label><select className="field-select" value={drawStudentId} onChange={e=>setDrawStudentId(e.target.value)}><option value="">Pick a student for me · equal chance</option>{students.map(s=><option key={String(s.id)} value={String(s.id)}>{s.name}</option>)}</select><div className="fair-note"><ShieldCheck size={17}/><span>Every active student has an equal chance. Prizes are picked at random from your active collection.</span></div><button className="primary-btn draw-now" disabled={spinning} onClick={draw}>{spinning?<><span className="spinner"/> Shaking the basket…</>:<><Sparkles size={17}/> Draw a reward</>}</button><p className="small-center">Your draw is saved to the student’s reward history.</p></section><section className="basket-panel"><div className={`basket-scene ${spinning?'shake':''}`}><div className="scene-star star-a">✦</div><div className="scene-star star-b">✧</div><div className="basket-emoji">🧺</div><div className="scene-prize p-a">⭐</div><div className="scene-prize p-b">🎨</div><div className="scene-prize p-c">📚</div></div><div className="basket-caption"><strong>{spinning?'A little anticipation…':'The surprise basket'}</strong><span>{prizes.length} lovely things inside · All prizes have equal odds</span></div></section></div><section className="recent-panel panel"><div className="section-heading compact"><div><h2>Recent celebrations</h2><p>Little moments worth remembering.</p></div><button className="text-link" onClick={()=>setTab('Reports')}>See reports <ArrowRight size={15}/></button></div>{draws.length?draws.slice(0,4).map((d,i)=><div className="draw-history" key={i}><span className="history-avatar">{d.avatar}</span><span><strong>{d.name}</strong><small>{d.prize}</small></span><span className="history-time">{d.at}</span></div>):<div className="empty-state"><div>🎁</div><strong>Your next happy memory starts here.</strong><span>Completed reward draws will show up here.</span></div>}</section></div>}
      {tab==='Classrooms'&&<div className="page-wrap alternate"><p className="eyebrow">YOUR LEARNING COMMUNITY</p><h1>Room to <em>grow.</em></h1><p className="subhead">Keep your classrooms and groups in one happy place.</p><div className="classroom-top"><div><h2>Your classrooms</h2><p>{classroomCards.length} classrooms · {groups.length} active groups</p></div><button className="primary-btn" onClick={()=>{setDraft('');setModal('newClass')}}><Plus size={16}/> New classroom</button></div><div className="classroom-grid">{classroomCards.map((c,i)=><article className="classroom-card" key={c.name}><div className={`classroom-banner ${c.tone}`}><span>{c.emoji}</span><button aria-label={`Archive ${c.name}`} className="icon-btn" onClick={()=>archiveClass(c.id)}><Archive size={17}/></button></div><div className="classroom-body"><h3>{c.name}</h3><p><GraduationCap size={14}/>{c.room}</p><div className="group-chips">{c.groups.map(g=><button onClick={()=>{setGroupId(g.id);setTab('Today')}} key={g.id}><span/> {g.name} <ChevronRight size={14}/></button>)}</div><button className="add-group" onClick={()=>setModal('groups')}><Plus size={15}/> Add a group</button></div></article>)}<button className="new-class-card" onClick={()=>{setDraft('');setModal('newClass')}}><span><Plus size={20}/></span><strong>Start a new classroom</strong><small>Organize a new learning group</small></button></div></div>}
      {tab==='Reports'&&<div className="page-wrap alternate"><p className="eyebrow">CELEBRATE EVERY STEP</p><h1>Look how far they’ve <em>come.</em></h1><p className="subhead">A little progress, all in one place.</p><div className="report-toolbar"><div className="group-picker"><Users size={16}/><select value={groupId} onChange={e=>setGroupId(e.target.value)}>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><ChevronDown size={15}/></div><div className="segmented">{['This week','This month'].map(p=><button key={p} className={period===p?'selected':''} onClick={()=>setPeriod(p)}>{p}</button>)}</div></div><div className="report-summary"><div className="report-hero"><span>YOUR GROUP’S GLOW</span><strong>{(reportData?.rows.reduce((sum,row)=>sum+Number(row.total||0),0)??0)}</strong><small>points earned {period==='This week'?'this week':'this month'} ✨</small><div className="report-doodles">✿ &nbsp;✦&nbsp; ✿</div></div><div className="report-stat"><span>TOP CRITERION</span><strong>{criteria[0]}</strong><small>{reportData?.rows.reduce((sum,row)=>sum+Number(row.homework_complete||0),0)??0} check-ins</small></div><div className="report-stat"><span>GROUP STREAK</span><strong>5 <small>days</small></strong><small>Look at you, Sunflowers!</small></div></div><section className="report-table panel"><div className="section-heading compact"><div><h2>Student progress</h2><p>Totals for {reportData?`${reportData.from} – ${reportData.to}`:'Loading date range…'}</p></div><button className="outline-btn" onClick={()=>notify('Report ready to print')}><Activity size={15}/> Print report</button></div><div className="table-scroll"><table><thead><tr><th>STUDENT</th>{criteria.map((c,i)=><th key={i} title={c}>{['Homework','Participation','Speaking','Project','Ready','Rules'][i]}</th>)}<th>TOTAL</th></tr></thead><tbody>{reportData?.rows.map((row,i)=><tr key={String(row.id)}><td><span className="table-student"><i>{({fox:'🦊',bear:'🐻',panda:'🐼',lion:'🦁',frog:'🐸',tiger:'🐯',koala:'🐨',unicorn:'🦄',penguin:'🐧',octopus:'🐙'} as Record<string,string>)[String(row.avatar_key)]||'🙂'}</i><strong>{String(row.display_name)}</strong></span></td>{['homework_complete','class_participation','speaking_effort','project_complete','class_readiness','speaking_day_rules'].map(key=><td key={key}>{Number(row[key]||0)}</td>)}<td><b>{Number(row.total||0)}</b></td></tr>)}</tbody><tfoot><tr><td>Group total</td>{['homework_complete','class_participation','speaking_effort','project_complete','class_readiness','speaking_day_rules'].map(key=><td key={key}>{reportData?.rows.reduce((sum,row)=>sum+Number(row[key]||0),0)??0}</td>)}<td>{(reportData?.rows.reduce((sum,row)=>sum+Number(row.total||0),0)??0)}</td></tr></tfoot></table></div></section><div className="report-note"><ShieldCheck size={16}/> Reports use your classroom’s local timezone. Days without a check-in count as zero points.</div></div>}
      {tab==='Settings'&&<div className="page-wrap alternate"><p className="eyebrow">YOUR CLASSROOM, YOUR WAY</p><h1>Make it feel like <em>yours.</em></h1><p className="subhead">A few little details to make BrightSteps work for you.</p><div className="settings-grid"><section className="panel settings-panel"><div className="panel-title"><div className="panel-icon purple"><Settings size={18}/></div><div><h2>Classroom settings</h2><p>Your classroom details and preferences.</p></div></div><label className="field-label">Tutor display name</label><input className="field-select" value={displayName} onChange={e=>setDisplayName(e.target.value)}/><label className="field-label">Timezone</label><select className="field-select" value={timezone} onChange={e=>setTimezone(e.target.value)}><option value={timezone}>{timezone}</option>{['Europe/Istanbul','Europe/London','Europe/Paris','America/New_York','America/Los_Angeles','Asia/Dubai','Asia/Tokyo','Australia/Sydney'].filter(t=>t!==timezone).map(t=><option key={t} value={t}>{t}</option>)}</select><label className="field-label">Current password (only needed to change password)</label><input className="field-select" type="password" autoComplete="current-password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)}/><label className="field-label">New password (12 characters minimum)</label><input className="field-select" type="password" autoComplete="new-password" value={newPassword} onChange={e=>setNewPassword(e.target.value)}/><button className="primary-btn" onClick={saveSettings}>Save changes</button></section><section className="panel settings-panel"><div className="panel-title"><div className="panel-icon gold"><Gift size={18}/></div><div><h2>Your prize collection</h2><p>Choose lovely, inclusive classroom rewards.</p></div></div>{prizes.map(p=><div className="prize-setting" key={p}><span>🎁</span><strong>{p}</strong><button aria-label={`Remove ${p}`} onClick={()=>deactivatePrize(p)}><X size={15}/></button></div>)}<button className="add-group" onClick={()=>{setDraft('');setModal('addPrize')}}><Plus size={15}/> Add a prize</button></section></div></div>}
    </section>
    {toast&&<div className="toast" role="status"><CheckCircle2 size={17}/>{toast}</div>}
    {modal&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setModal('')}}><div className="modal" role="dialog" aria-modal="true"><button className="modal-close icon-btn" aria-label="Close" onClick={()=>setModal('')}><X size={18}/></button><div className="modal-emoji">{modal==='addStudent'?'👋':modal==='addPrize'?'🎁':modal==='groups'?'🌈':'🏫'}</div><h2>{modal==='addStudent'?'A new little learner':modal==='addPrize'?'Add a happy surprise':modal==='groups'?'Choose a classroom group':modal==='newGroup'?'Add a group':'A new classroom'}</h2><p>{modal==='groups'?'Pick a group to see how everyone is doing.':modal==='addStudent'?'Add a student to '+group+'.':modal==='addPrize'?'Add a simple, inclusive classroom reward.':modal==='newGroup'?'Add a grade or class group to your first classroom.':'Give your new learning community a name.'}</p>{modal==='groups'?<><div className="modal-groups">{groups.map(g=><button key={g.id} onClick={()=>{setGroupId(g.id);setModal('');setTab('Today')}}>{g.classroom_name} · {g.name}<ChevronRight size={16}/></button>)}</div><button className="add-group" onClick={()=>{setDraft('');setModal('newGroup')}}><Plus size={15}/> Add a group</button></>:<><label className="field-label" htmlFor="draft">{modal==='addStudent'?'Student name':modal==='addPrize'?'Prize name':modal==='newGroup'?'Group name':'Classroom name'}</label><input autoFocus id="draft" className="field-select" value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){modal==='addStudent'?addStudent():modal==='addPrize'?addPrize():modal==='newGroup'?createNewGroup(draft):createClass(draft);if(modal==='newClass'){setModal('');setDraft('');}}}} placeholder={modal==='addStudent'?'e.g. Sam Taylor':modal==='addPrize'?'e.g. Choose the class game':modal==='newGroup'?'e.g. Grade 3 Sunflowers':'e.g. Tuesday reading group'}/><button className="primary-btn modal-submit" onClick={()=>modal==='addStudent'?addStudent():modal==='addPrize'?addPrize():modal==='newGroup'?createNewGroup(draft):createClass(draft)}><Plus size={16}/> {modal==='addStudent'?'Add student':modal==='addPrize'?'Add prize':modal==='newGroup'?'Create group':'Create classroom'}</button></>}</div></div>}
    {winner&&<div className="reveal-backdrop" role="dialog" aria-modal="true" aria-label="Reward reveal"><div className="confetti-layer" aria-hidden="true">{Array.from({length:28},(_,i)=><i key={i} style={{left:`${(i*37)%100}%`,animationDelay:`${(i%9)*.13}s`,background:['#ef7560','#e9b947','#51a89b','#8c78bf'][i%4]}}/>)}</div><button className="reveal-close icon-btn" aria-label="Close reveal" onClick={()=>setWinner(null)}><X size={20}/></button><div className="reveal-card"><div className="reveal-spark">✦</div><span className="kicker">TODAY’S LITTLE CELEBRATION</span><div className="winner-avatar">{winner.avatar}</div><p>Today’s surprise goes to</p><h2>{winner.name}!</h2><div className="prize-reveal"><span>🎁</span><strong>{winner.prize}</strong></div><p className="reveal-sub">A little kindness goes a long way. ✨</p><button className="primary-btn" onClick={()=>setWinner(null)}>Lovely! <Heart size={15}/></button></div></div>}
  </main>;
}

function FlameIcon(){return <span className="flame">✦</span>}
